baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Blog: A blog about R and other stuff"
description = ""
theme = "kube"
googleAnalytics = ""
disqusShortname = "lksmth"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Projects"
    url = "/projects/"
[[menu.main]]
    name = "Packages"
    url = "/packages/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

