baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Welcome"
description = "Please checkout my website"
theme = "kube"
googleAnalytics = ""
disqusShortname = "lksmth"
ignoreFiles = ["\\.Rmd$", "\\.RData$", "_files$", "_cache$"]

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Projects"
    url = "/projects/"
[[menu.main]]
    name = "Packages"
    url = "/packages/"

[Params]
    author = "Luke Smith"
    github = "seasmith"
    stackoverflow = "5228718"
    twitter = "lksmth"
    linkedin = "lksmth"
    email = "lukedansmi@sbcglobal.net"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "sql"]
    highlightjsTheme = "hybrid"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

