---
title  : "US Rig Counts"
author : "Luke Smith"
date   : "2017-10-06"
tags   : [r, oil, gas, oil and gas, rig counts]
description: ""
twitter :
  card    : "summary_large_image"
  site    : "@lksmth"
  creator : "@lksmth"
  title   : "US Rig Counts"
  description : ""
  image       : ""
og :
  image : ""

---

```{r setup_std, include=FALSE}
# source("setup_std.R")

# ---- Library_Tidyverse_Setup
library(plyr)
library(tidyverse)
library(lubridate)
library(forcats)
library(stringi)

# ---- Library_ploting_Setup
library(grid)
library(gridExtra)
library(ggExtra)
library(GGally)
library(ggalt)
library(scales)
library(extrafont)
loadfonts("win")

# ---- Library_Web_Setup
library(rvest)
library(jsonlite)

# ---- Library_Reporting_Setup
library(knitr)
library(kableExtra)

# ---- My_Blogging_Setup
library(blg)

# ---- Opts_Setup
knitr::opts_chunk$set(echo =  FALSE)
knitr::opts_chunk$set(fig.height = 7)
knitr::opts_chunk$set(message    = FALSE)
knitr::opts_chunk$set(warning    = FALSE)


# ---- R_Options_Setup
old_scipen <- getOption("scipen")
options(scipen = 100)

old_digits <- getOption("digits")
options(digits = 2)


# ---- knitr_Options_Setup
orig_inline <- knit_hooks$get("inline")
old_plot   <- knit_hooks$get("plot")


# ---- Hooks_Setup

knit_hooks$set(inline = function(x) {
  if (is.numeric(x) | is.integer(x)) return(formatC(x, format = "d", big.mark = ",")) else
    if (is.character(x)) return(stringr::str_to_title(x)) else
      return(x)
})

old_inline <- knit_hooks$get("inline")

my_blue   <- "#0059B3"
my_orange <- "#B35A00"
my_pink   <- "#B30059"
my_green  <- "#59B300"
```

```{r setup_extra, include=FALSE}
library(readxl)
library(sf)
library(forcats)
```

```{r import_oil_price, include=FALSE, eval=FALSE}
api_key_fred <- blg_source_value("api_key_fred.R")

api_url <- "https://api.stlouisfed.org/fred/"
req_type <- "series/observations"
req_qry <- "?series_id="
api_qry <- "&api_key="
file_type <- "&file_type="

fred_qry <- paste0(api_url, req_type,
                   req_qry, "DCOILWTICO",
                   api_qry, api_key_fred,
                   file_type, "json")

oil_prices <- fred_qry %>%
  read_html() %>%
  html_text() %>%
  fromJSON() %>%
  .[["observations"]] %>%
  as_tibble() %>%
  select(-(1:2))

oil_prices <- oil_prices %>%
  mutate(value = as.double(value),
         date  = as.Date(date)) %>%
  rename(price = value)
```

```{r notes_data, include=FALSE}
# Earliest splits by:
#   * Basin      = 2011
#   * State      = 2000
#   * Oil & Gas  = 1987
#   * Trajectory = 1991
#   * GOM        = 2000
#   * Canada (Province)  = 2003
#   * Canada (Oil & Gas) = 2000

# Basin names in rig counts:
# Order        Basin_Name
#     1  Ardmore Woodford
#     2   Arkoma Woodford
#     3           Barnett
#     4     Cana Woodford
#     5       DJ-Niobrara
#     6        Eagle Ford
#     7      Fayetteville
#     8      Granite Wash
#     9       Haynesville
#    10         Marcellus
#    11     Mississippian
#    12           Permian
#    13             Utica
#    14         Williston
#    15            Others
#    16 Total US RigCount
```

```{r import_data_rig_counts_exp, include=FALSE, eval=FALSE}
url <- "http://phx.corporate-ir.net/phoenix.zhtml?c=79687&p=irol-reportsother"
h <- url %>% read_html()

trs <- h %>%
  html_nodes(xpath = '//div[contains(@class, "site-width")]//div[contains(@class, "content-rail")]//div[contains(@class, "rig-content-fleft")]') %>%
  html_nodes(xpath = '//table[contains(@class, "rigCountTbl")]') %>%
  html_nodes(xpath = '//table//table//table//tr')

trs_odd <- trs %>%
  html_nodes(xpath = '//tr//span[contains(@class, "ccbnTblOdd")]//a[contains(@class, "ccbnTblLnk")]')

trs_even <- trs %>%
  html_nodes(xpath = '//tr//span[contains(@class, "ccbnTblEven")]//a[contains(@class, "ccbnTblLnk")]')


# Pivot Table (Sheet 2: "Master Data")
which_pivot <- trs_odd %>%
  html_text() %>%
  grepl("North America Rotary Rig Count Pivot Table \\(Feb 2011 - Current\\) ", .)

pivot <- trs_odd %>%
  .[which_pivot] %>%
  html_attr("href") %>%
  download.file("~/R/misc/oil/rig_counts/pivot_table.xlsb", mode = "wb")

which_count <- trs_odd %>%
  html_text() %>%
  grepl("North America Rotary Rig Count \\(Jan 2000 - Current\\) ", .)

count <- trs_odd %>%
  .[which_count] %>%
  html_attr("href") %>%
  download.file("~/R/misc/oil/rig_counts/count.xlsb", mode = "wb")
```

```{r import_data_rig_counts, include=FALSE}
# ---- count.xlsx
wb_1 <- "~/R/misc/oil/rig_counts/count.xlsx"
  
sh_nms_1 <- excel_sheets(wb_1)

bsn_sheet <- sh_nms_1[grepl("Basin", sh_nms_1)]
trj_sheet <- sh_nms_1[grepl("Trajectory", sh_nms_1)]
gom_sheet <- sh_nms_1[grepl("Gulf of Mexico", sh_nms_1)]

basin <- read_excel(wb_1, bsn_sheet, skip = 10)
basin <- seq.int(2, 65) %>%  # Create seq along columns except `Date`
  split(ceiling(seq_along(.) / 4)) %>%  # Split into groups of 4
  map(~gather(select(basin, 1, .x), ... = -Date))  # Gather the groups of four
bsn_nms <- read_excel(wb_1, bsn_sheet, "B10:BM10")
bsn_nms <- names(bsn_nms)[seq.int(1, length(bsn_nms), 4)]
names(basin) <- bsn_nms
basin <- basin %>% bind_rows(.id = "basin")

# trj <- read_excel(wb_1, trj_sheet, skip = 5)

# ---- pivot_table.xlsx
wb_2 <- "~/R/misc/oil/rig_counts/pivot_table.xlsx"
sh_nms_2 <- excel_sheets(wb_2)

mstr_sheet <- sh_nms_2[grepl("^Master Data$", sh_nms_2)]
# mstr <- read_excel(wb_2, mstr_sheet) # Causes Windows to die!
mstr <- read_csv("~/R/misc/oil/rig_counts/mstr.csv")
```

```{r wrangle_data_rig_counts, include=FALSE}
basin <- basin %>%
  mutate(key = case_when(
    grepl("Oil", key) ~ "Oil",
    grepl("Gas", key) ~ "Gas",
    grepl("Misc", key) ~ "Misc",
    grepl("Total", key) ~ "Total"
    ))

mstr <- mstr %>%
    mutate(Basin = if_else(Basin == "Dj-Niobrara", "DJ-Niobrara", Basin))
```

```{r analyze_data_rig_counts, include=FALSE}
theme_set(blg_theme_default())
previous <- sort(unique(basin$Date))[length(unique(basin$Date)) - 1]
current <- sort(unique(basin$Date))[length(unique(basin$Date))]

last_yr <- basin %>%
    distinct(Date) %>%
    arrange(desc(Date)) %>%
    .$Date %>%
    .[53]

this_wk <- basin %>%
    distinct(Date) %>%
    arrange(desc(Date)) %>%
    .$Date %>%
    .[1]

# Find most recent week's change from previous week; Total
current_total <- basin %>%
  mutate(value = as.integer(value)) %>%
  group_by(basin, key) %>%
  arrange(Date) %>%
  mutate(chng_1wk = (value - lag(value)) / lag(value),
         chng_4wk = (value - lag(value, 4)) / lag(value, 4),
         chng_16wk = (value - lag(value, 16)) / lag(value, 16),
         chng_52wk = (value - lag(value, 52)) / lag(value, 52)) %>%
  ungroup() %>%
  filter(Date == current) %>%
  filter(key == "Total")

# Find most recent week's oil and gas type
current_type <- basin %>%
  mutate(value = as.integer(value)) %>%
  group_by(basin, key) %>%
  arrange(Date) %>%
  mutate(chng_1wk = (value - lag(value)) / lag(value),
         chng_4wk = (value - lag(value, 4)) / lag(value, 4),
         chng_16wk = (value - lag(value, 16)) / lag(value, 16),
         chng_52wk = (value - lag(value, 52)) / lag(value, 52)) %>%
  ungroup() %>%
  filter(Date == current) %>%
    filter(key != "Total")

current_type <- current_type %>%
    select(basin:value) %>%
    filter(key != "Misc") %>%
    spread(key, value) %>%
    mutate(prcnt_oil = Oil / (Oil + Gas))

# Remove NaN's and NA's for plotting purposes
current_total <- current_total %>%
  mutate_at(vars(chng_1wk, chng_52wk), function(x) if_else(is.na(x), 0, x))

# Create levels vector
ct_levels <- current_total %>%
  arrange(desc(chng_1wk), basin) %>%
  .$basin

# Assign levels
current_total <- current_total %>%
  mutate(basin = factor(basin, levels = ct_levels))

# Those with zero percent change
zeros <- current_total %>%
    filter(chng_1wk == 0)

# Weekly summary
summ <- basin %>%
  group_by(key, Date) %>%
  summarize(value = sum(value, na.rm = TRUE))

# ---- Summarize mstr
# Total rig count by `Year` and `Week`

mstr_total <- mstr %>%
  filter(Country == "UNITED STATES") %>%
  group_by(PublishDate, Basin) %>%
  summarize(RigCount = sum(RigCount, na.rm = TRUE)) %>%
  ungroup()

mstr_total <- mstr_total %>%
  add_column(Trajectory = "Total")

mstr_type <- mstr %>%
  filter(Country == "UNITED STATES") %>%
  select(-Country, -WellDepth, -(Year:Week)) %>%
  group_by(Basin, Trajectory, PublishDate) %>%
  summarize(RigCount = sum(RigCount, na.rm = TRUE)) %>%
  ungroup()

mstr_type <- mstr_type %>%
    union_all(mstr_total) %>%
    spread(Trajectory, RigCount) %>%
    mutate(hz = Horizontal / Total)
```

```{r import_sf_data, include=FALSE}
sf_plays_orig <- st_read("~/R/misc/oil/US/eia_shape/TightOil_ShaleGas_Plays_Lower48_EIA/TightOil_ShalePlays_US_EIA_May2016.shp")

sf_basins <- st_read("~/R/misc/oil/US/eia_shape/SedimentaryBasins_US_EIA/SedimentaryBasins_US_May2011_v2.shp")

load("~/R/misc/maps/states_map.RData")
```

```{r import_drawn_data, include=FALSE}
granite_wash <- structure(list(Basin = "Granite Wash", feature_type = "polygon", 
    geometry = structure(list(structure(list(structure(c(-99.9976, 
    -100.2063, -100.3436, -100.5469, -100.6787, -100.8435, -100.8545, 
    -100.8215, -100.6787, -100.5029, -100.3079, -100.1129, -99.7229, 
    -99.4263, -99.2725, -99.1296, -99.0088, -98.9978, -99.1516, 
    -99.3823, -99.4592, -99.5581, -99.7339, -99.9976, 35.7733, 
    35.8623, 35.9202, 36.0313, 36.0757, 36.0846, 35.9869, 35.9157, 
    35.8089, 35.6751, 35.5412, 35.407, 35.1379, 35.021, 34.976, 
    34.976, 34.976, 35.084, 35.1828, 35.2815, 35.3532, 35.4338, 
    35.5859, 35.7733), .Dim = c(24L, 2L))), class = c("XY", "POLYGON", 
    "sfg"))), n_empty = 0L, precision = 0, class = c("sfc_POLYGON", 
    "sfc"), bbox = structure(c(-100.8545, 34.976, -98.9978, 36.0846
    ), .Names = c("xmin", "ymin", "xmax", "ymax"), class = "bbox"), crs = structure(list(
        epsg = 4326L, proj4string = "+proj=longlat +datum=WGS84 +no_defs"), .Names = c("epsg", 
    "proj4string"), class = "crs")), Lithology = NA, Shale_play = "Granite Wash", 
    Source = "Hand Drawn", Area_sq_mi = NA, Area_sq_km = NA, 
    Age_shale = NA), row.names = c(NA, -1L), class = c("sf", 
"data.frame"), sf_column = "geometry", agr = structure(c(NA_integer_, 
NA_integer_), class = "factor", .Label = c("constant", "aggregate", 
"identity"), .Names = c("Basin", "feature_type")), .Names = c("Basin", 
"feature_type", "geometry", "Lithology", "Shale_play", "Source", 
"Area_sq_mi", "Area_sq_km", "Age_shale"))

mississippian <- structure(list(Basin = "Mississippian", feature_type = "polygon", 
    geometry = structure(list(structure(list(structure(c(-98.5474, 
    -99.0747, -99.4263, -99.5142, -99.2285, -98.6572, -97.4268, 
    -96.5918, -96.1523, -95.8887, -95.6909, -95.5151, -95.6909, 
    -96.1084, -97.0752, -97.7563, -98.5474, 36.3151, 36.4213, 
    36.6155, 37.0201, 37.2653, 37.3178, 37.4225, 37.3352, 37.1778, 
    37.1078, 36.9499, 36.6684, 36.3505, 36.2088, 36.2266, 36.2974, 
    36.3151), .Dim = c(17L, 2L))), class = c("XY", "POLYGON", 
    "sfg"))), n_empty = 0L, precision = 0, class = c("sfc_POLYGON", 
    "sfc"), bbox = structure(c(-99.5142, 36.2088, -95.5151, 37.4225
    ), .Names = c("xmin", "ymin", "xmax", "ymax"), class = "bbox"), crs = structure(list(
        epsg = 4326L, proj4string = "+proj=longlat +datum=WGS84 +no_defs"), .Names = c("epsg", 
    "proj4string"), class = "crs")), Lithology = NA, Shale_play = "Mississippian", 
    Source = "Hand Drawn", Area_sq_mi = NA, Area_sq_km = NA, 
    Age_shale = NA), row.names = c(NA, -1L), class = c("sf", 
"data.frame"), sf_column = "geometry", agr = structure(c(NA_integer_, 
NA_integer_), class = "factor", .Label = c("constant", "aggregate", 
"identity"), .Names = c("Basin", "feature_type")), .Names = c("Basin", 
"feature_type", "geometry", "Lithology", "Shale_play", "Source", 
"Area_sq_mi", "Area_sq_km", "Age_shale"))
```

```{r wrangle_data, include=FALSE}
states_48 <- states_map %>%
  filter(NAME %in% c(state.name, "District of Columbia")) %>%
  filter(!(NAME %in% c("Alaska", "Hawaii"))) %>%
  filter(TYPE != "Water")

sf_plays <- sf_plays_orig %>%
  filter(Shale_play != "Heath") %>%
    mutate(Shale_play = case_when(
      Basin == "Ardmore"  ~ "Ardmore Woodford",
      Basin == "Arkoma" & Shale_play != "Fayetteville"  ~ "Arkoma Woodford",
      Basin == "Anadarko" ~ "Cana Woodford",
      Basin == "Williston" ~ "Williston",
      Basin == "Permian" ~ "Permian",
      Basin == "Denver Basin" ~ "DJ-Niobrara",
      TRUE ~ as.character(Shale_play)
    ))

granite_wash <- granite_wash %>%
  select(-feature_type) %>%
  st_cast("MULTIPOLYGON")
mississippian <- mississippian %>%
  select(-feature_type) %>%
  st_cast("MULTIPOLYGON")

sf_plays <- sf_plays %>%
  rbind(granite_wash) %>%
  rbind(mississippian) %>%
  filter(Shale_play %in% current_total$basin)

# ---- Merge MULTIPOLYGONS
# Split and union (i.e. dissolve/merge) multi's
new_geometry <- sf_plays %>%
  split(.$Shale_play) %>%
  .[unlist(lapply(., function(x) nrow(x) > 1))] %>%
  map(~st_cast(st_sf(st_union(.x)), "MULTIPOLYGON")) %>%
  reduce(rbind)

# Get rid of duplicates
grouped_sf_plays <- sf_plays %>% group_by(Shale_play)
new_sf_plays <- grouped_sf_plays %>% filter(!(n() > 1))
dupe_sf_plays <- grouped_sf_plays %>% filter(n() > 1) %>% slice(c(1, nrow(.)))

st_geometry(dupe_sf_plays) <- st_geometry(new_geometry)
sf_plays <- new_sf_plays %>%
  rbind(dupe_sf_plays)

# ---- Create text table for `geom_text()`
# Find centroid of each feature to use as (x, y) for text
sf_text <- sf_plays %>%
  st_centroid()

# Extract coordinates
sf_text <- sf_text %>%
  st_coordinates() %>%
  cbind(as_tibble(sf_text), .)

tst <- sf_text %>%
  cbind(tibble(offset_X = c( 5.8,  1.7, # Ardmore,      Fayetteville
                             3.8,  5.4, # Barnett,      Arkoma
                            -5.6, -4.8, # Cana,  Eagle Ford
                            -4.5, -5.7, # DJ-Niobrara, Marcellus
                            -5.4, -4.1, # Utica, Granite Wash
                             0.0, -3.8, # Mississippian, Permian
                            -3.7))) %>% # Williston
  cbind(tibble(offset_Y = c(-0.8,  0.9, # Ardmore,      Fayetteville
                            -0.5, -0.5, # Barnett,      Arkoma
                             1.1, -0.5, # Cana,  Eagle Ford
                            -1.0, -2.7, # DJ-Niobrara, Marcellus
                             0.0,  0.0, # Utica, Granite Wash
                             1.5,  1.0, # Mississippian, Permian
                            -1.0))) %>% # Williston
  mutate(X = X + offset_X,
         Y = Y + offset_Y)

tst_proj <- tst %>%
    mutate(new_X = X + offset_X,
           new_Y = Y + offset_Y,

           new_X = case_when(
             Shale_play == "Ardmore Woodford" ~ new_X * 1.072, #$ + pos
             Shale_play == "Fayetteville" ~ new_X * 1.03,      #$ + pos
             Shale_play == "Barnett" ~ new_X * 1.05,           #$ + pos
             Shale_play == "Arkoma Woodford" ~ new_X * 1.07,   #$ + pos
             Shale_play == "Cana Woodford" ~ new_X * 0.95,     #$ - neg
             Shale_play == "Eagle Ford" ~ new_X * 0.955,       #$ - neg
             Shale_play == "DJ-Niobrara" ~ new_X * 0.96,       #$ - neg
             Shale_play == "Marcellus" ~ new_X * 0.94,         #$ - neg
             Shale_play == "Utica" ~ new_X * 0.935,            #$ - neg
             Shale_play == "Granite Wash" ~ new_X * 0.96,      #$ - neg
             Shale_play == "Mississippian" ~ new_X * 1.00,     #$ 0
             Shale_play == "Permian" ~ new_X * 0.9675,         #$ - neg
             Shale_play == "Williston" ~ new_X * 0.985         #$ - neg
             ),
           new_Y = case_when(
             Shale_play == "Ardmore Woodford" ~ new_Y * 1.038, #$ - neg
             Shale_play == "Fayetteville" ~ new_Y * 0.975,     #$ + pos
             Shale_play == "Barnett" ~ new_Y * 1.00,           #$ - neg
             Shale_play == "Arkoma Woodford" ~ new_Y * 1.02,   #$ - neg
             Shale_play == "Cana Woodford" ~ new_Y * 0.97,     #$ + pos
             Shale_play == "Eagle Ford" ~ new_Y * 1.035,       #$ - neg
             Shale_play == "DJ-Niobrara" ~ new_Y * 1.04,       #$ - neg
             Shale_play == "Marcellus" ~ new_Y * 1.079,        #$ - neg
             Shale_play == "Utica" ~ new_Y * 1.00,             #$ 0
             Shale_play == "Granite Wash" ~ new_Y * 1.00,      #$ 0
             Shale_play == "Mississippian" ~ new_Y * 0.96,     #$ + pos
             Shale_play == "Permian" ~ new_Y * 0.95,           #$ 0
             Shale_play == "Williston" ~ new_Y * 1.05          #$ - neg
             )) %>%
    st_as_sf(coords = c("new_X", "new_Y"), crs = 4326, agr = "identity") %>%
    st_transform(102003)

tst_proj <- tst_proj %>%
    select(-(X:Y)) %>%
    st_coordinates() %>%
    cbind(as_tibble(tst_proj %>% select(-(X:Y))), .)

# ---- Merge datasets with sf data
sf_plays_total <- sf_plays %>%
  merge(current_total, by.x = "Shale_play", by.y = "basin")

sf_current_type <- sf_plays %>%
  merge(current_type, by.x = "Shale_play", by.y = "basin")
```

```{r join_data, include=FALSE, eval=FALSE}
jt <- oil_prices %>%
    group_by(ym = as.yearmon(date)) %>%
    summarise(price = mean(price, na.rm = TRUE)) %>%
    inner_join(trajectory %>%
                   group_by(ym = as.yearmon(Date)) %>%
                   summarise_at(vars(Directional, Horizontal, Vertical, TOTAL), mean), by = "ym")
```

```{r plots, fig.height=9}
# Create blank geom to hold plots
gb <- ggplot() +
  geom_blank() +
  labs(title = "Rigging up, rigging down",
       subtitle = paste0("Where did rig counts change from the week of ", previous, " to\n",
                         current, "?")) +
  theme(axis.title = element_blank()) +
  theme(plot.caption = element_text("Open Sans", colour = "gray30", size = 12))

# ---- Map
wk1_colors <- current_total$chng_1wk %>%
  sign() %>%
  unique()

map_colors <- switch(as.character(sum(wk1_colors + c(2, 4, 6))),
       "2" = blg_colors$red,
       "3" = "gray70",
       "5" = c(blg_colors$red, "gray70"),
       "7" = blg_colors$blue,
       "9" = c(blg_colors$red, blg_colors$blue),
       "10" = c("gray70", blg_colors$blue),
       "12" = c(blg_colors$red, "gray70", blg_colors$blue))

rc_map <- sf_plays_total %>%
  ggplot() +
  geom_sf(data = states_48, fill = "white", color = "gray60") +
  geom_sf(aes(fill = factor(sign(chng_1wk))),
          color = "gray50",
          alpha = 0.9) +
  geom_text(data = tst, aes(X, Y, label = Shale_play), size = 3) +
  scale_fill_manual(name = NULL,
                    values = map_colors,
                    labels = c("Decrease", "No Change", "Increase")) +
  # scale_color_manual(values = map_colors) +
  coord_sf(crs = st_crs(sf_plays_total), datum = NA) +
  guides(color = FALSE,
         alpha = FALSE) +
  theme(axis.title = element_blank()) +
  theme(plot.caption = element_text("Open Sans", colour = "gray30", size = 12)) +
  theme(legend.position = c(0.95, 0.1),
        legend.justification = c("right", "bottom"),
        legend.box.just = "right")

# ---- Change from week ago
  # Create levels vector
    chng_1wk_levels <- current_total %>%
      arrange(desc(chng_1wk), basin) %>%
      .$basin
  
  # Assign levels
  current_total <- current_total %>%
    mutate(basin = factor(basin, levels = chng_1wk_levels))
  
wk1_colors <- switch(sum(wk1_colors) + 2,
                      blg_colors$red, # when only negative change
                      c(blg_colors$blue, blg_colors$red), # when both
                      blg_colors$blue) # when only positive change

  
rc_chng_1wk <- current_total %>%
  filter(basin != "Total US RigCount") %>%
  filter(chng_1wk != 0 & !is.infinite(chng_52wk)) %>%
  ggplot() +
  geom_col(aes(fct_rev(basin), chng_1wk, fill = chng_1wk < 0)) +
  coord_flip() +
  scale_fill_manual(values = wk1_colors) +
  scale_y_continuous(labels = blg_frmt_percent(1)) +
  guides(fill = FALSE) +
  labs(title = "Percent change from\nprevious week",
       x = NULL,
       y = NULL) +
  blg_theme_default(12)

# ---- Change from year ago
  # Create levels vector
  chng_52wk_levels <- current_total %>%
    arrange(desc(chng_52wk), basin) %>%
    .$basin
  
  # Assign levels
  current_total <- current_total %>%
    mutate(basin = factor(basin, levels = chng_52wk_levels))

wk52_colors <- current_total$chng_52wk %>%
  sign() %>%
  unique()

wk52_colors <- switch(sum(wk52_colors) + 2,
                      blg_colors$red, # when only negative change
                      c(blg_colors$blue, blg_colors$red), # when both
                      blg_colors$blue) # when only positive change

rc_chng_52wk <- current_total %>%
  filter(basin != "Total US RigCount") %>%
  filter(chng_52wk != 0 & !is.infinite(chng_52wk)) %>%
  ggplot() +
  geom_col(aes(fct_rev(basin), chng_52wk, fill = chng_52wk < 0)) +
  coord_flip() +
  scale_fill_manual(values = wk52_colors) +
  scale_y_continuous(labels = blg_frmt_percent(1)) +
  guides(fill = FALSE) +
  labs(title = "Percent change from\nprevious year",
       x = NULL,
       y = NULL) +
  blg_theme_default(12)


# ---- Total current rig total
rc_total <- current_total %>%
  filter(basin != "Total US RigCount") %>%
  arrange(value) %>%
  mutate(basin = factor(basin, levels = basin)) %>%
  ggplot() +
  geom_col(aes(basin, value), fill = blg_colors$green) +
  labs(title = "\nTotal rig count",
       x = NULL,
       y = NULL) +
  blg_theme_default(12) +
  rotateTextX(30, vjust = 1)

# Dummy plot for the map legend
dummy <- ggplot(mtcars) +
    geom_bar(aes(cyl, fill = factor(cyl))) +
    scale_fill_manual(name = "Change in\nrig count",
                      values = c(blg_colors$red, "gray50", blg_colors$blue),
                      labels = c("Decrease", "No Change", "Increase"))

d_grob <- ggplotGrob(dummy)
lgnd   <- d_grob$grobs[[which(d_grob$layout$name == "guide-box")]]

rc_grobs <- arrangeGrob(rc_map, rc_chng_1wk, rc_chng_52wk,
                        layout_matrix = rbind(c(1, 1),
                                              c(2, 3)))
# grid.draw(rc_grobs)

gb_grob <- ggplotGrob(gb)
gb_grob$grobs[[which(gb_grob$layout$name == "panel")]] <- gb_grob$grobs[[which(gb_grob$layout$name == "panel")]] %>%
  addGrob(rc_grobs)

grid.draw(gb_grob)
```

```{r more_plots, fig.height=9}
rc_type <- summ %>%
  filter(key != "Misc") %>%
  ggplot() +
  geom_line(aes(Date, value, color = key), size = 0.7) +
  scale_color_manual(values = c(my_green, my_pink, "black")) +
  labs(title = "Rig count by well type",
       y = "Rig count") +
  blg_theme_default(12)

# ---- Oil/Gas type concept map
gb <- ggplot() +
  geom_blank() +
  labs(title = "The hot commodity",
       subtitle = paste0("What are rigs after these days?")) +
  theme(axis.title = element_blank()) +
  theme(plot.caption = element_text("Open Sans", colour = "gray30", size = 12))

rt_map <- sf_current_type %>%
  ggplot() +
  geom_sf(data = states_48, fill = "white", color = "gray60") +
  geom_sf(aes(fill = prcnt_oil),
          color = "black",
          alpha = 0.9) +
  geom_text(data = tst_proj, aes(X, Y, label = Shale_play), size = 3) +
  scale_fill_gradient(name = NULL,
                      low = my_green,
                      high = my_pink,
                      na.value = "gray70",
                      labels = c("100% Gas", "", "Split", "", "100% Oil")) +
  coord_sf(crs = st_crs(102003), datum = NA) +
  guides(alpha = FALSE) +
  theme(axis.title = element_blank()) +
  theme(plot.caption = element_text("Open Sans", colour = "gray30", size = 12),
        legend.position = c(0.85, 0.08),
        legend.justification = c("left", "bottom"),
        legend.box.just = "right")

gb_grob <- ggplotGrob(gb)
# rt_map <- ggplotGrob(rt_map)

rt_grobs <- arrangeGrob(rt_map, rc_type, layout_matrix = rbind(c(1, 1),
                                                      c(2, 2)))

gb_grob$grobs[[which(gb_grob$layout$name == "panel")]] <- gb_grob$grobs[[which(gb_grob$layout$name == "panel")]] %>%
  addGrob(rt_grobs)

grid.draw(gb_grob)
```

```{r exp, include=FALSE}
ckey <- basin %>%
  group_by(basin, key) %>%
  arrange(Date) %>%
  mutate(chng_1wk = (value - lag(value)) / value,
         chng_4wk = (value - lag(value, 4)) / value,
         chng_16wk = (value - lag(value, 16)) / value,
         chng_52wk = (value - lag(value, 52)) / value) %>%
  ungroup() %>%
  filter(Date == current) %>%
  filter(key != "Total")

ckey <- ckey %>%
  mutate(basin = factor(basin, levels = ct_levels))

ckey <- ckey %>%
  mutate(chng_1wk = if_else(is.na(chng_1wk), 0, chng_1wk))

ckey %>%
  select(basin:chng_1wk) %>%
  spread(key, value) %>%
  filter(chng_1wk != 0)
```

```{r exp_plot, include=FALSE, eval=FALSE}
# ---- GIF
# tweenr
library(tweenr)
t <- mstr_type %>% select(Basin, PublishDate, hz)

# NEED TO SPLIT BY `PublishDate` NOT `id`!!!
t_tween <- t %>%
    rename(x = PublishDate, y = hz, id = Basin) %>%
    mutate(id = factor(id)) %>%
    split(.$id) %>%
    .[c(-1, -7)] %>%
    tweenr::tween_states(1, 0.5, "linear", nframe = 300)

t_tween <- t_tween %>%
    mutate(PublishDate = x, Basin = id) %>%
    inner_join(t)

# ggplot2
p <- ggplot(t_tween, aes(id, y, frame = .frame)) +
    geom_point()

# gganimate
library(gganimate)
gganimate(p)

# ---- Other
current_total %>%
  filter(basin != "Total US RigCount") %>%
  ggplot() +
  geom_point(aes(fct_rev(basin), chng_1wk, color = factor(sign(chng_1wk)), size = value)) +
  geom_segment(aes(x = basin, xend = basin, y = 0, yend = chng_1wk, color = factor(sign(chng_1wk)))) +
  # geom_text(data = zeros, aes(basin, chng_1wk),
  #           label = "X", fontface = "bold") +
  coord_flip() +
  scale_color_manual(name = "Change",
                     values = c(blg_colors$red, "black", blg_colors$blue)) +
  scale_size_continuous(name = "Number of rigs") +
  scale_y_continuous(labels = blg_frmt_percent(1),
                     limits = c(-0.05, 0.05),
                     breaks = c(-0.05, -0.025, 0, 0.025, 0.05)
                     ) +
  guides(color = FALSE) +
  labs(title = "US rig count (lower 48 states)",
       subtitle = paste0("Percent change in rig count from week of\n",
                         previous, " to ", current),
       x = paste0("Basin"),
       y = paste0("Percent change in rigs")) +
  blg_theme_default(14)
```
