---
title  : "Colorado Oil and Gas Production"
author : "Luke Smith"
date   : "2017-09-20"
tags   : [colorado, oil and gas, oil and gas production]
description: ""
---

```{r setup_std, include=FALSE}
# source("setup_std.R")

# ---- Library_Tidyverse_Setup
library(plyr)
library(tidyverse)
library(lubridate)
library(forcats)
library(stringi)

# ---- Library_ploting_Setup
library(grid)
library(gridExtra)
library(ggExtra)
library(GGally)
library(ggalt)
library(scales)
library(extrafont)
loadfonts("win")

# ---- Library_Web_Setup
library(rvest)
library(jsonlite)

# ---- Library_Reporting_Setup
library(knitr)
library(kableExtra)



# ---- Opts_Setup
knitr::opts_chunk$set(echo =  FALSE)
knitr::opts_chunk$set(fig.height = 7)
knitr::opts_chunk$set(message    = FALSE)
knitr::opts_chunk$set(warning    = FALSE)



# ---- R_Options_Setup
org_scipen <- getOption("scipen")
options(scipen = 100)

org_digits <- getOption("digits")
options(digits = 2)



# ---- knitr_Options_Setup
org_inline <- knit_hooks$get("inline")
org_plot   <- knit_hooks$get("plot")



# ---- Hooks_Setup

knit_hooks$set(inline = function(x) {
  if (is.numeric(x) | is.integer(x)) return(formatC(x, format = "d", big.mark = ",")) else
    if (is.character(x)) return(stringr::str_to_title(x)) else
      return(x)
})

mod_inline <- knit_hooks$get("inline")



# ---- Extra_Function_Setup
# -- Find days in a year
days_in_year <- function(date) {
    c(366, 365)[c(lpyr <- lubridate::leap_year(date), !lpyr)]
}

# -- Control how percentages are formatted
my_percent <- function(x, i = 1) {
  sprintf(sprintf("%s%s%s", "%.", i, "f%%"), x * 100)
}

# -- Convert listified JSON data into a nested tibble
to_tibble <- function(x) {
    isdf <- unname(which(unlist(map(x, is.data.frame))))
    isndf <- seq_along(x)[-isdf]
    tbbl <- add_column(bind_cols(x[isndf]), x[isdf])
    names(tbbl)[isdf] <- names(x)[isdf]
    names(tbbl)[isndf] <- names(x)[isndf]
    return(tbbl)
}

# -- Row bind a list into a tibble
bind_list_rows <- function(list_rows) {
    tibble::as_tibble(data.table::rbindlist(list_rows))
}

# -- Union a list of tibbles into a single tibble
bind_list_tibbles <- function(list_tibbles){
  purrr::reduce(list_tibbles, function(...) dplyr::union_all(...))
}

# -- Source and return only the .$value
source_value <- function(file) {
  stopifnot(file.exists(file))
  value <- source(file, echo = FALSE)
  value <- value["value"][[1]]
}

# -- Capitalize
capitalize <- function(string) {
  substr(string, 1, 1) <- toupper(substr(string, 1, 1))
  string
}

# -- Default theme
theme_default <- function(text_size = 16) {
  theme_minimal() +
    theme(panel.grid.minor = element_blank(),
                text = element_text(family = "Open Sans",
                                    size = text_size),
                complete = TRUE)
}

  # ---- Color_Setup ----
# Plot set up
my_red        <- "#ce1141"
my_red2       <- "#a33c56"
# my_verylight_red <- 
my_lightred   <- "#fabdcd"
my_darkred    <- "#870b2b"
my_blue       <- "#4fa8ff"
my_blue2      <- "#1141ce"
my_purple     <- "#8E3694"
my_lightgreen <- "#198f5a"
my_lightgreen_2 <- "#329b6c"
my_lightgreen_3 <- "#4ca87e"
my_lightgreen_4 <- "#66b491"
my_verylight_green   <- "#e5f2ec"
my_verylight_green_2 <- "#cce6da"
my_verylight_green_3 <- "#b2d9c8"
my_green      <- "#008348"
my_green_2    <- "#007540"
my_green_3    <- "#006839"
my_green_4    <- "#005b32"
my_green_5    <- "#004e2b"
my_green_6    <- "#004124"
my_darkgreen   <- "#00341c"
my_darkgreen_2 <- "#002715"
my_darkgreen_3 <- "#001a0e"
my_orange     <- "#e15c39"
my_orange2    <- "#834800"


```


```{r}
url <- "http://cogcc.state.co.us/data2.html#/downloads"

wells_url <- "http://cogcc.state.co.us/documents/data/downloads/gis/WELLS_SHP.ZIP"
```

```{r}
prod_folder <- "~/R/misc/oil/Colorado/production"

prod_files <- prod_folder %>% list.files(full.names = TRUE)
prod_ext <- prod_files %>% tools::file_ext()
outcome <- prod_files[prod_ext == "zip"] %>% map(unzip, exdir = prod_folder)
```


```{r}
prod_files <- prod_folder %>% list.files(full.names = TRUE)
prod_ext <- prod_files %>% tools::file_ext()

prod_meta <- "http://cogcc.state.co.us/documents/data/downloads/production/production_record_data_dictionary.htm" %>%
  read_html() %>%
  html_nodes("table") %>%
  html_table(header = TRUE) %>%
  .[[1]]

col_nms <- prod_meta %>%
  .$Field

col_tps <- c("c", "i", rep("c", 6),
             "i", "c", rep("i", 8),
             "d", rep("i", 9),
             rep("c", 3), "T", "c")

copro <- prod_files[prod_ext == "csv"] %>%
  map(read_csv, col_names = FALSE)

save(copro, file = "~/R/misc/oil/Colorado/production/copro.RData")
```

```{r}
# What are the column classes?
cols_class <- copro %>%
    map(~map(.x, class)) %>%
    modify_depth(2, function(x) if (any(grepl("POSIX", x))) "date" else x) %>%
    bind_rows()

# Which column classes are off?
cols_off <- cols_class %>%
    map(unique) %>%
    {which(lengths(.) != 1)}

# Show what "off" columns' class for each list element (row in tibble)
cols_class %>%
  select(unname(cols_off))

# What do columns need to be converted to?
cols_convert_to <- c(rep("integer", 5), "date", "character")

# Convert to integer
copro <- copro %>%
    map(~mutate_at(.x, vars(X17, X21, X23, X26, X27), as.integer))

# Convert to date
copro <- copro %>%
    map(~mutate_at(.x, vars(X32), as.Date))

copro <- copro %>%
    bind_rows()

names(copro) <- prod_meta$Field

save(copro, file = "~/R/misc/oil/Colorado/production/copro.RData")
```


```{r}
set.seed(99)

ctest <- copro %>%
    sample_frac(0.01)

save(ctest, file = "~/R/misc/oil/Colorado/production/ctest.RData")
```

```{r}
load("~/R/misc/oil/Colorado/production/ctest.RData")

miss_graph <- ctest %>%
  as_shadow() %>%
  mutate(rnum = row_number()) %>%
  gather(... = -rnum)
```
