---
title  : "Getting Data From the Web With R"
author : "Luke Smith"
date   : "2017-06-07"
tags   : [r, web, internet, importing, scraping]
---

This post is not limited to just one type of getting (scraping, requesting, etc) or one source from which things are _got_ (API, attached file, HTML table, etc).

I've decided to place the methods in order of _unobviousness_.

### XHR

If you know about XHR, then you probably won't want to read this post, since it is likely that you know all of these methods.

When websites, especially those with D3 or other JavaScript graphics, are building, they often send XMLHttpRequests for data. Most JS vizualization libraries build on the _client-side_, therefore it is likely when these are present that there is a data file hidden behind the XHR.

#### Example

The New York Times and Washington Post make use of JS visualizations quite a bit.


### Commented-Out Table
There are generally two ways to handle a table which has been commented-out:

* Extract comments and read as new HTML
* Run a headless browser (GhostJS, Headless Chrome)

Within your web-browser, such HTML tables will appear as HTML tables. This is because your web-browser executes necessary JS code to render the tables.

### Hidden API
These API's aren't a secret nor are they (well) hidden. These are sites where the API request commands are not made available to you, and nor is an API key made available.


#### Example

The North Dakota Department of Natural Resources has a well viewer page, where you can request data from...


