---
title  : "OPEC"
author : "Luke Smith"
date   : ""
tags   : []
description: ""
twitter :
  card    : "summary_large_image"
  site    : "@lksmth"
  creator : "@lksmth"
  title   : ""
  description : ""
  image       : ""
og :
  image : ""
---

Links:
https://www.bloomberg.com/news/articles/2017-09-12/opec-is-said-to-discuss-extending-oil-cuts-by-more-than-3-months
https://www.bloomberg.com/graphics/2017-opec-production-targets/?utm_content=graphics&utm_campaign=socialflow-organic&utm_source=twitter&utm_medium=social&cmpid%3D=socialflow-twitter-graphics


```{r setup_std, include=FALSE}
# source("setup_std.R")

# ---- Library_Tidyverse_Setup
library(tidyverse)
library(lubridate)
library(forcats)
library(stringi)

# ---- Library_ploting_Setup
library(grid)
library(gridExtra)
library(ggExtra)
library(GGally)
library(ggalt)
library(scales)
library(extrafont)
loadfonts("win")

# ---- Library_Web_Setup
library(rvest)
library(jsonlite)

# ---- Library_Reporting_Setup
library(knitr)
library(kableExtra)

# ---- My_Blogging_Setup
library(blg)

# ---- Opts_Setup
knitr::opts_chunk$set(echo =  FALSE)
knitr::opts_chunk$set(fig.height = 7)
knitr::opts_chunk$set(message    = FALSE)
knitr::opts_chunk$set(warning    = FALSE)


# ---- R_Options_Setup
old_scipen <- getOption("scipen")
options(scipen = 100)

old_digits <- getOption("digits")
options(digits = 2)


# ---- knitr_Options_Setup
orig_inline <- knit_hooks$get("inline")
old_plot   <- knit_hooks$get("plot")


# ---- Hooks_Setup

knit_hooks$set(inline = function(x) {
  if (is.numeric(x) | is.integer(x)) return(formatC(x, format = "d", big.mark = ",")) else
    if (is.character(x)) return(stringr::str_to_title(x)) else
      return(x)
})

old_inline <- knit_hooks$get("inline")

my_blue   <- "#0059B3"
my_orange <- "#B35A00"
my_pink   <- "#B30059"
my_green  <- "#59B300"
```

```{r setup_extra, include=FALSE}
library(magick)
# Mask rvest::pluck with purrr:pluck
pluck <- purrr::pluck
```

```{r import_oil_price, include=FALSE, eval=FALSE}
api_url <- "https://api.stlouisfed.org/fred/"
req_type <- "series/observations"
req_qry <- "?series_id="
api_qry <- "&api_key="
api_key_fred <- getOption("api_key_fred")
file_type <- "&file_type="

fred_qry <- paste0(api_url, req_type,
                   req_qry, "DCOILWTICO",
                   api_qry, api_key_fred,
                   file_type, "json")

oil_prices <- fred_qry %>%
  read_html() %>%
  html_text() %>%
  fromJSON() %>%
  .[["observations"]] %>%
  as_tibble() %>%
  select(-(1:2))

oil_prices <- oil_prices %>%
  mutate(value = as.double(value),
         date  = as.Date(date)) %>%
  rename(price = value)
```

```{r import_oil_production_meta, include=FALSE, eval=FALSE}
# ----
# Set query
# ----

api_url <- "http://api.eia.gov/"
req_cat <- "category/"
api_qry <- "?api_key="
qry_cat <- "&category_id="
qry_id  <- 2134979
api_key_eia  <- getOption("api_key_eia")

eia_qry <- paste0(api_url,
                  req_cat,
                  api_qry, api_key_eia,
                  qry_cat, qry_id)

# ----
# Make request
# ----

jdata <- eia_qry %>%
  read_html() %>%
  html_text() %>%
  fromJSON()
```

```{r tidy_meta, include=FALSE}
# ----
# Get data
# ----

series_meta <- jdata %>%
  pluck("category") %>%
  pluck("childseries") %>%
  as_tibble()

# ----
# Get series_id for download
# of each series
# ----

qry_id <- series_meta %>%
    filter(f == "M" & units == "Thousand Barrels Per Day") %>%
    pull("series_id")

# ----
# Get meta for database
# ----

parent_category_id <- jdata %>%
  pluck("category") %>%
  pluck("parent_category_id")

category_tbl_nm <- "International Crude Oil and Lease Condensate Production"
```

```{r import_oil_production_data, include=FALSE}
# ----
# Set query
# ----

req_srs <- "series/"
qry_srs <- "&series_id="

eia_qry <- qry_id %>%
  map_chr(~paste0(api_url,
                  req_srs,
                  api_qry, api_key_eia,
                  qry_srs, .x))

# ----
# Make request
# ----

prod_list <- map(eia_qry,
                 ~fromJSON(html_text(read_html(.x))))
```


```{r tidy_data, include=FALSE}
# ----
# Get meta for data joining and database
# ----

# The meta is hidden somewhere
prod_meta <- map(prod_list,
                 ~.x$series[, !grepl("data", names(.x$series))])
prod_meta <- bind_rows(prod_meta)
prod_meta <- as_tibble(prod_meta)

# ----
# Get the data
# ----

# The data is also hidden
prod_data <- map(prod_list,
                 ~.x$series[, grepl("data", names(.x$series))][[1]])
prod_data <- map(prod_data,
                 as_tibble)
names(prod_data) <- prod_meta$series_id
prod_data <- prod_data %>% bind_rows(.id = "series_id")

# ----
# Make the data better
# ----

# Need to know more than numbers and id's
prod <- prod_data %>%
  left_join(prod_meta %>%
              select(series_id, geography:updated),
            "series_id")
# Better names would help, too
prod <- prod %>%
  rename(date = V1, production = V2)

# Country names work better than abbreviations
ISO_3166_1 <- ISOcodes::ISO_3166_1 %>% as_tibble()

# Some of these production values are not numbers
not_numbers <- prod %>%
  filter(grepl("[^0-9+\\.0-9+]", production)) %>%
  count(geography) %>%
  left_join(ISO_3166_1, by = c("geography" = "Alpha_3"))

prod <- prod %>%
  mutate(date = as.Date(paste0(date, "01"), format = "%Y%m%d"),
         production = as.double(production))

# Add those names
prod <- prod %>%
  left_join(ISO_3166_1 %>% select(Alpha_3, Name), by = c("geography" = "Alpha_3")) %>%
  select(Name, date, production, everything())

# save original (nostalgia)
prod_orig <- prod

# Get rid of non-existant countries (those without names)
prod <- prod %>%
  filter(!is.na(Name))
```

```{r post_recession_analysis, include=FALSE}
start_date <- as.Date("2007-06-01")
end_date   <- as.Date("2017-06-01")

# Everything "post recession" OR TEN YEARS?
post_recession <- prod %>%
    filter(between(date, start_date, end_date)) %>%
    group_by(Name) %>%
    arrange(desc(date)) %>%
    ungroup()

# Production at start of period.
# 
# Starting period changes because South Sudan
# was not a country until 2011
#
# This is a more dynamic way of getting the
# index year of each country.
#
# However, Jordan and Slovenia have no production
# value (all NA)
init <- prod %>%
  filter(date <= end_date) %>%
  filter(date >= start_date) %>%
  group_by(Name) %>%
  arrange(date) %>%
  filter(!is.na(production)) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%
  rename(init_prod = production) %>%
  select(Name, init_prod)

# Mash the three
post_recession <- post_recession %>%
  left_join(init, by = "Name")

# Production at end of period
end <- prod %>%
  filter(date == end_date) %>%
  rename(end_prod = production) %>%
  select(Name, end_prod)

post_recession <- post_recession %>%
  left_join(end, by = "Name")

# Do the math
post_recession <- post_recession %>%
  mutate(index = (production / init_prod) * 100,
         init_change = production - init_prod,
         sign = sign(end_prod - init_prod)) %>%
  select(Name, date, index, production, everything())

post_recession <- post_recession %>%
    mutate(sign = case_when(
        sign == 1  ~ "positive",
        sign == 0  ~ "neutral",
        sign == -1 ~ "negative",
        TRUE       ~ "neither"
    ))
```

```{r plot_post_recession, include=FALSE}
# Jordan and Slovenia have no production value (all NA)
post_recession2 <- post_recession %>%
    filter(!grepl("Jordan|Slovenia", Name)) 

Names <- unique(post_recession2$Name)

td <- tempdir()

map_chr(Names, ~{
  gg <- ggplot(post_recession2,
               aes(date, init_change,
                   group = Name,
                   color = sign)) +
    geom_line(alpha = 1/3) +
    geom_line(data = filter(post_recession2, Name == .x)) +
    scale_x_date("Date",
                 limits = c(as.Date("2006-01-01"),
                            as.Date("2018-01-01"))) +
    scale_y_continuous(paste0("Production change",
                              "\n(Thousand Barells)"),
                       limits = c(-2000, 4500)) +
    scale_alpha_manual(NULL,
                       values = c(0.3, 1)) +
    labs(title = paste0("Bringing down the house"),
         subtitle = paste0("Which oil producer caused the most havoc for oil prices?")) +
    theme(axis.title.y.left = element_text(angle = 90))
  
  fil <- file.path(td, sprintf("%04d.png", as.integer(.x)))

  ggsave(fil, gg, , units = "in", width=6, height=3.5)
  
  fil
  }) %>% 
  map(image_read) %>%
  map(image_scale, geometry = "675x") %>%
  image_join() %>% 
  image_animate() %>% 
  image_write("ani.gif")
```

```{r}
post_tst <- post_recession %>%
  filter(grepl("United States|Saudi", Name))

td <- tempdir()

scale_marker <- as.Date("2011-02-01")

thin_lims <- post_tst %>%
  filter(date <= scale_marker) %>%
  filter(init_change %in% c(min(init_change), max(init_change))) %>%
  arrange(init_change) %>%
  pull(init_change)

wide_lims <- post_tst %>%
  filter(date > scale_marker) %>%
  filter(init_change %in% c(min(init_change), max(init_change))) %>%
  arrange(init_change) %>%
  pull(init_change)

wide_lims <- c(min(thin_lims, wide_lims),
               max(thin_lims, wide_lims))

date_iterator <- post_tst %>%
  distinct(date) %>%
  add_row(date = rep(scale_marker, 20)) %>%
  add_row(date = rep(max(.$date), 20)) %>%
  arrange(date) %>%
  add_column(id = seq(1, nrow(.)))

# Label country lines
sa_y  <-  900
or_y  <-  350
usa_y <- -150

labels <- date_iterator %>%
  filter(date == max(date) | date == scale_marker) %>%
  mutate(saudi_label = case_when(date == scale_marker ~ "Saudi Arabia",
                                 TRUE ~ NA_character_),
         sa_y   = case_when(date == scale_marker   ~ sa_y,
                               TRUE ~ NA_real_),
         or_label  = case_when(between(row_number(), 7, 21)  ~ "or",
                               TRUE ~ NA_character_),
         or_y      = case_when(between(row_number(), 7, 21)  ~ or_y,
                               TRUE ~ NA_real_),
         usa_label = case_when(between(row_number(), 13, 21) ~ "The United
                               States",
                               TRUE ~ NA_character_),
         usa_y     = case_when(between(row_number(), 13, 21) ~ usa_y,
                               TRUE ~ NA_real_))

# Explain the y-axis values and the starting point
explainers <- tribble(
  ~axis, ~date,
  "Change in production", paste0("From this date", "\nJune 2007")
  )

# Label x-offsets
sa_offset_x  <- 180
or_offset_x  <- 225
usa_offset_x <- 540

# Arrow tables
data_arrow <- filter(post_tst, date == scale_marker)

sa_arrow <- tibble(id = filter(labels, !is.na(saudi_label))$id)
sa_arrow <- sa_arrow %>%
  add_column(x = scale_marker + sa_offset_x,
             y = sa_y,
             x_end = scale_marker,
             y_end = filter(data_arrow, Name == "Saudi Arabia")$init_change)

usa_arrow <- tibble(id = filter(labels, !is.na(usa_label))$id)
usa_arrow <- usa_arrow %>%
  add_column(x = scale_marker + usa_offset_x,
             y = usa_y,
             x_end = scale_marker,
             y_end = filter(data_arrow, Name == "Untied States")$init_change)

map2_chr(date_iterator$date, date_iterator$id, ~{
  # Set y-limits
  lims <- if (.x <= scale_marker) thin_lims else NULL
  gg <- ggplot(filter(post_tst, date <= .x)) +
    geom_line(aes(date, init_change,
                  group = Name,
                  alpha = Name == "United States",
                  size  = Name == "United States")) +
    scale_alpha_manual(values = c(0.6, 1)) +
    scale_size_manual(values = c(0.6, 1)) +
    scale_x_date(limits = c(as.Date("2007-01-01"), as.Date("2018-01-01")),
                 minor_breaks = NULL) +
    scale_y_continuous(limits = lims) +
    guides(alpha = FALSE, size = FALSE) +
    labs(title = paste0("Who put more pressure on the",
                        "\noil markets?"),
         x = paste0("Date"),
         y = paste0("Change in production",
                    "\nfrom 2007-06-01 (Thousand Barrels)"),
         caption = paste0("Source: US Energy Information Administration")) +
    theme(axis.title = element_text(size = 11)) +
    theme(plot.caption = element_text("Open Sans", colour = "gray30", size =
                                        10))
  # Add text at appropriate times
  if (.x == scale_marker) {
    d  <- filter(labels, id == .y)
    gg <- gg +
      geom_text(data = d,
                aes(date, saudi_y, label = saudi_label),
                alpha = 0.6, size = 4, nudge_x = sa_offset_x) +
      geom_text(data = d,
                aes(date, or_y, label = or_label),
                size = 5, nudge_x = or_offset_x) +
      geom_text(data = d,
                aes(date, usa_y, label = usa_label),
                alpha = 1, size = 6, nudge_x = usa_offset_x)
    }

  fil <- file.path(td, sprintf("%s.png", as.character(.y)))
  ggsave(fil, gg, , units = "in", width=6, height=3.5)
  fil
  
}) %>%
  map(image_read) %>%
  map(image_scale, geometry = "675x") %>%
  image_join() %>%
  image_animate() %>%
  image_write("prod2.gif")
```
