---
title: "Population And GDP"
author: "Luke Smith"
date: "`r Sys.Date()`"
tags: [mexico, asylum, refugees]
description: ""
twitter :
  card    : "summary_large_image"
  site    : "@lksmth"
  creator : "@lksmth"
  title   : "Population And GDP"
  description : ""
  image       : ""
og :
  image : ""
---

```{r knitr-setup, include=FALSE}
library(knitr)

opts_chunk$set(include=FALSE)
opts_chunk$set(message=FALSE)
opts_chunk$set(warning=FALSE)
```


```{r}
library(tidyverse)
library(lubridate)
library(blg)
```

```{r setup-misc}
nation_lookup <- tibble::tribble(
  ~country,  ~region, ~global_hemisphere,
  "Andorra",               "Europe",  "Global.North",
  "United Arab Emirates",         "Arab States", "Global South",
  "Afghanistan",      "Asia & Pacific", "Global South",
  "Antigua and Barbuda", "South/Latin America", "Global South",
  "Anguilla", "South/Latin America", "Global South",
  "Albania",              "Europe", "Global North",
  "Armenia",              "Europe", "Global South",
  "Netherlands Antilles", "South/Latin America", "Global South",
  "Angola",              "Africa", "Global South",
  "Antarctica",      "Asia & Pacific", "Global South",
  "Argentina", "South/Latin America", "Global South",
  "American Samoa",      "Asia & Pacific", "Global South",
  "Austria",              "Europe", "Global North",
  "Australia",      "Asia & Pacific", "Global North",
  "Aruba", "South/Latin America", "Global South",
  "Azerbaijan",      "Asia & Pacific", "Global South",
  "Bosnia and Herzegovina",              "Europe", "Global North",
  "Barbados", "South/Latin America", "Global South",
  "Bangladesh",      "Asia & Pacific", "Global South",
  "Belgium",              "Europe", "Global North",
  "Burkina Faso",              "Africa", "Global South",
  "Bulgaria",              "Europe", "Global North",
  "Bahrain",         "Arab States", "Global South",
  "Burundi",              "Africa", "Global South",
  "Benin",              "Africa", "Global South",
  "Bermuda",       "North America", "Global North",
  "Brunei Darussalam",      "Asia & Pacific", "Global South",
  "Bolivia", "South/Latin America", "Global South",
  "Brazil", "South/Latin America", "Global South",
  "Bahamas", "South/Latin America", "Global South",
  "Bhutan",      "Asia & Pacific", "Global South",
  "Bouvet Island", "South/Latin America", "Global South",
  "Botswana",              "Africa", "Global South",
  "Belarus",              "Europe", "Global South",
  "Belize", "South/Latin America", "Global South",
  "Canada",       "North America", "Global North",
  "Cocos (Keeling) Islands",      "Asia & Pacific", "Global South",
  "Congo, The Democratic Republic of the",              "Africa", "Global South",
  "Central African Republic",              "Africa", "Global South",
  "Congo",              "Africa", "Global South",
  "Switzerland",              "Europe", "Global North",
  "Côte D'Ivoire",              "Africa", "Global South",
  "Cook Islands",      "Asia & Pacific", "Global South",
  "Chile", "South/Latin America", "Global South",
  "Cameroon",              "Africa", "Global South",
  "China",      "Asia & Pacific", "Global South",
  "Colombia", "South/Latin America", "Global South",
  "Costa Rica", "South/Latin America", "Global South",
  "Cuba", "South/Latin America", "Global South",
  "Cape Verde",              "Africa", "Global South",
  "Christmas Island",      "Asia & Pacific", "Global South",
  "Cyprus",              "Europe", "Global North",
  "Czech Republic",              "Europe", "Global North",
  "Germany",              "Europe", "Global North",
  "Djibouti",         "Arab States", "Global South",
  "Denmark",              "Europe", "Global North",
  "Dominica", "South/Latin America", "Global South",
  "Dominican Republic", "South/Latin America", "Global South",
  "Algeria",         "Arab States", "Global South",
  "Ecuador", "South/Latin America", "Global South",
  "Estonia",              "Europe", "Global North",
  "Egypt",         "Arab States", "Global South",
  "Western Sahara",              "Africa", "Global South",
  "Eritrea",              "Africa", "Global South",
  "Spain",              "Europe", "Global North",
  "Ethiopia",              "Africa", "Global South",
  "Finland",              "Europe", "Global North",
  "Fiji",      "Asia & Pacific", "Global South",
  "Falkland Islands (Malvinas)", "South/Latin America", "Global South",
  "Micronesia, Federated States of",      "Asia & Pacific", "Global South",
  "Faroe Islands",              "Europe", "Global North",
  "France",              "Europe", "Global North",
  "France, Metropolitan",              "Europe", "Global North",
  "Gabon",              "Africa", "Global South",
  "United Kingdom",              "Europe", "Global North",
  "Grenada", "South/Latin America", "Global South",
  "Georgia",              "Europe", "Global South",
  "French Guiana", "South/Latin America", "Global South",
  "Ghana",              "Africa", "Global South",
  "Gibraltar",              "Europe", "Global North",
  "Greenland",              "Europe", "Global North",
  "Gambia",              "Africa", "Global South",
  "Guinea",              "Africa", "Global South",
  "Guadeloupe", "South/Latin America", "Global South",
  "Equatorial Guinea",              "Africa", "Global South",
  "Greece",              "Europe", "Global North",
  "South Georgia and the South Sandwich Islands", "South/Latin America", "Global South",
  "Guatemala", "South/Latin America", "Global South",
  "Guam",      "Asia & Pacific", "Global South",
  "Guinea-Bissau",              "Africa", "Global South",
  "Guyana", "South/Latin America", "Global South",
  "Hong Kong",      "Asia & Pacific", "Global North",
  "Heard Island and McDonald Islands",      "Asia & Pacific", "Global South",
  "Honduras", "South/Latin America", "Global South",
  "Croatia",              "Europe", "Global North",
  "Haiti", "South/Latin America", "Global South",
  "Hungary",              "Europe", "Global North",
  "Indonesia",      "Asia & Pacific", "Global South",
  "Ireland",              "Europe", "Global North",
  "Israel",              "Europe", "Global North",
  "India",      "Asia & Pacific", "Global South",
  "British Indian Ocean Territory",      "Asia & Pacific", "Global South",
  "Iraq",         "Arab States", "Global South",
  "Iran, Islamic Republic of",      "Asia & Pacific", "Global South",
  "Iceland",              "Europe", "Global North",
  "Italy",              "Europe", "Global North",
  "Jamaica", "South/Latin America", "Global South",
  "Jordan",         "Arab States", "Global South",
  "Japan",      "Asia & Pacific", "Global North",
  "Kenya",              "Africa", "Global South",
  "Kyrgyzstan",      "Asia & Pacific", "Global South",
  "Cambodia",      "Asia & Pacific", "Global South",
  "Kiribati",      "Asia & Pacific", "Global South",
  "Comoros",         "Arab States", "Global South",
  "Saint Kitts and Nevis", "South/Latin America", "Global South",
  "Korea, Democratic People's Republic of",      "Asia & Pacific", "Global South",
  "Korea, Republic of",      "Asia & Pacific", "Global North",
  "Kuwait",         "Arab States", "Global South",
  "Cayman Islands", "South/Latin America", "Global South",
  "Kazakhstan",      "Asia & Pacific", "Global South",
  "Lao People's Democratic Republic",      "Asia & Pacific", "Global South",
  "Lebanon",         "Arab States", "Global South",
  "Saint Lucia", "South/Latin America", "Global South",
  "Liechtenstein",              "Europe", "Global North",
  "Sri Lanka",      "Asia & Pacific", "Global South",
  "Liberia",              "Africa", "Global South",
  "Lesotho",              "Africa", "Global South",
  "Lithuania",              "Europe", "Global North",
  "Luxembourg",              "Europe", "Global North",
  "Latvia",              "Europe", "Global North",
  "Libya",         "Arab States", "Global South",
  "Morocco",         "Arab States", "Global South",
  "Monaco",              "Europe", "Global North",
  "Moldova, Republic of",              "Europe", "Global North",
  "Madagascar",              "Africa", "Global South",
  "Marshall Islands",      "Asia & Pacific", "Global South",
  "Macedonia",              "Europe", "Global North",
  "Mali",              "Africa", "Global South",
  "Myanmar",      "Asia & Pacific", "Global South",
  "Mongolia",      "Asia & Pacific", "Global South",
  "Macau",      "Asia & Pacific", "Global North",
  "Northern Mariana Islands",      "Asia & Pacific", "Global South",
  "Martinique", "South/Latin America", "Global South",
  "Mauritania",         "Arab States", "Global South",
  "Montserrat", "South/Latin America", "Global South",
  "Malta",              "Europe", "Global North",
  "Mauritius",              "Africa", "Global South",
  "Maldives",      "Asia & Pacific", "Global South",
  "Malawi",              "Africa", "Global South",
  "Mexico", "South/Latin America", "Global South",
  "Malaysia",      "Asia & Pacific", "Global South",
  "Mozambique",              "Africa", "Global South",
  "Namibia",              "Africa", "Global South",
  "New Caledonia",      "Asia & Pacific", "Global South",
  "Niger",              "Africa", "Global South",
  "Norfolk Island",      "Asia & Pacific", "Global South",
  "Nigeria",              "Africa", "Global South",
  "Nicaragua", "South/Latin America", "Global South",
  "Netherlands",              "Europe", "Global North",
  "Norway",              "Europe", "Global North",
  "Nepal",      "Asia & Pacific", "Global South",
  "Nauru",      "Asia & Pacific", "Global South",
  "Niue",      "Asia & Pacific", "Global South",
  "New Zealand",      "Asia & Pacific", "Global North",
  "Oman",         "Arab States", "Global South",
  "Panama", "South/Latin America", "Global South",
  "Peru", "South/Latin America", "Global South",
  "French Polynesia",      "Asia & Pacific", "Global South",
  "Papua New Guinea",      "Asia & Pacific", "Global South",
  "Philippines",      "Asia & Pacific", "Global South",
  "Pakistan",      "Asia & Pacific", "Global South",
  "Poland",              "Europe", "Global North",
  "Saint Pierre and Miquelon",       "North America", "Global North",
  "Pitcairn Islands",      "Asia & Pacific", "Global South",
  "Puerto Rico", "South/Latin America", "Global South",
  "Palestinian Territory",         "Arab States", "Global South",
  "Portugal",              "Europe", "Global North",
  "Palau",      "Asia & Pacific", "Global South",
  "Paraguay", "South/Latin America", "Global South",
  "Qatar",         "Arab States", "Global South",
  "Reunion",      "Asia & Pacific", "Global South",
  "Romania",              "Europe", "Global North",
  "Russian Federation",              "Europe", "Global North",
  "Rwanda",              "Africa", "Global South",
  "Saudi Arabia",         "Arab States", "Global South",
  "Solomon Islands",      "Asia & Pacific", "Global South",
  "Seychelles",              "Africa", "Global South",
  "South Sudan",              "Africa", "Global South",
  "Sudan",         "Arab States", "Global South",
  "Sweden",              "Europe", "Global North",
  "Singapore",      "Asia & Pacific", "Global North",
  "Saint Helena",              "Africa", "Global South",
  "Slovenia",              "Europe", "Global North",
  "Svalbard and Jan Mayen",              "Europe", "Global North",
  "Slovakia",              "Europe", "Global North",
  "Sierra Leone",              "Africa", "Global South",
  "San Marino",              "Europe", "Global North",
  "Senegal",              "Africa", "Global South",
  "Somalia",         "Arab States", "Global South",
  "Suriname", "South/Latin America", "Global South",
  "Sao Tome and Principe",              "Africa", "Global South",
  "El Salvador", "South/Latin America", "Global South",
  "Syrian Arab Republic",      "Asia & Pacific", "Global South",
  "Swaziland",              "Africa", "Global South",
  "Turks and Caicos Islands", "South/Latin America", "Global South",
  "Chad",              "Africa", "Global South",
  "French Southern Territories",      "Asia & Pacific", "Global South",
  "Togo",              "Africa", "Global South",
  "Thailand",      "Asia & Pacific", "Global South",
  "Tajikistan",      "Asia & Pacific", "Global South",
  "Tokelau",      "Asia & Pacific", "Global South",
  "Turkmenistan",      "Asia & Pacific", "Global South",
  "Tunisia",         "Arab States", "Global South",
  "Tonga",      "Asia & Pacific", "Global South",
  "Timor-Leste",      "Asia & Pacific", "Global South",
  "Turkey",              "Europe", "Global North",
  "Trinidad and Tobago", "South/Latin America", "Global South",
  "Tuvalu",      "Asia & Pacific", "Global South",
  "Taiwan",      "Asia & Pacific", "Global North",
  "Tanzania, United Republic of",              "Africa", "Global South",
  "Ukraine",              "Europe", "Global South",
  "Uganda",              "Africa", "Global South",
  "United States Minor Outlying Islands",      "Asia & Pacific", "Global South",
  "United States",       "North America", "Global North",
  "Uruguay", "South/Latin America", "Global South",
  "Uzbekistan",      "Asia & Pacific", "Global South",
  "Holy See (Vatican City State)",              "Europe", "Global North",
  "Saint Vincent and the Grenadines", "South/Latin America", "Global South",
  "Venezuela", "South/Latin America", "Global South",
  "Virgin Islands, British", "South/Latin America", "Global South",
  "Virgin Islands, U.S.", "South/Latin America", "Global South",
  "Vietnam",      "Asia & Pacific", "Global South",
  "Vanuatu",      "Asia & Pacific", "Global South",
  "Wallis and Futuna",      "Asia & Pacific", "Global South",
  "Samoa",      "Asia & Pacific", "Global South",
  "Yemen",         "Arab States", "Global South",
  "Mayotte",              "Africa", "Global South",
  "Serbia",              "Europe", "Global North",
  "South Africa",              "Africa", "Global South",
  "Zambia",              "Africa", "Global South",
  "Montenegro",              "Europe", "Global North",
  "Zimbabwe",              "Africa", "Global South",
  "Aland Islands",              "Europe", "Global North",
  "Guernsey",              "Europe", "Global North",
  "Isle of Man",              "Europe", "Global North",
  "Jersey",              "Europe", "Global North",
  "Saint Barthelemy", "South/Latin America", "Global South",
  "Saint Martin", "South/Latin America", "Global South",
  "Anonymous Proxy",             "Unknown",      "Unknown",
  "Satellite Provider",             "Unknown",      "Unknown",
  "Other",             "Unknown",      "Unknown",
  "Asia/Pacific Region",      "Asia & Pacific",      "Unknown",
  "Europe",              "Europe",      "Unknown",
  "Invalid IP",             "Unknown",      "Unknown",
  "Libyan Arab Jamahiriya",             "Unknown",      "Unknown",
  "Bonaire, Saint Eustatius and Saba",             "Unknown",      "Unknown",
  "Sint Maarten (Dutch part)",             "Unknown",      "Unknown",
  "Curaçao",             "Unknown",      "Unknown"
)
```

```{r import-data, eval=FALSE}
source("01_import_national-population.R")
source("01_import_national-gdp.R")
source("01_import_state-gdp.R")
source("02_tidy_national-population.R")
source("02_tidy_national-gdp.R")
source("02_tidy_state-gdp.R")
```

```{r load-data}
load("pop_data.RData")
load("gdp_data.RData")
load("gsp_data.RData")
```

```{r tidy-merge}
nations <- pop_data %>%
  rename(population = value) %>%
  select(-Nation, -realtime_end, -realtime_start) %>%
  left_join(
    gdp_data %>%
      rename(gdp = value) %>%
      select(-Nation, -realtime_end, -realtime_start, -title)
    , by = c("Nation2", "date")) %>%
  select(date, population, gdp, nation = title, Nation2)
```

```{r tidy-summarize}
nations <- nations %>%
  group_by(nation) %>%
  mutate(gdp_per_capita = gdp / population,
         gdp_per_capita_growth = (gdp_per_capita - lag(gdp_per_capita, 1)) / lag(gdp_per_capita, 1),
         population_growth = (population - lag(population, 1)) / lag(population, 1),
         gdp_growth = (gdp - lag(gdp, 1)) / lag(gdp, 1)) %>%
  ungroup()
```

```{r}
opts_chunk$set(include=TRUE)
opts_chunk$set(echo=FALSE)
opts_chunk$set(message=FALSE)
opts_chunk$set(warning=FALSE)
```

```{r cor-all-countries-2010-present}
nations %>%
  filter(year(date) >= 2010) %>%
  ggplot(aes(population_growth, gdp_per_capita_growth)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", se = FALSE, color = "orange", size = 1.0) +
  blg_theme_default(13) 

nations %>%
  filter(year(date) >= 2010) %>%
  {cor.test(.$population_growth, .$gdp_per_capita_growth)}
```

```{r cor-europe-2010-present}
nation_lookup %>%
  filter(str_detect(region, "Europe")) %>%
  anti_join(nations, ., by = c("nation" = "country")) %>%
  filter(year(date) >= 2010) %>%
  ggplot(aes(population_growth, gdp_per_capita_growth)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", se = FALSE, color = "orange", size = 1.0) +
  blg_theme_default(13)

nation_lookup %>%
  filter(str_detect(region, "Europe")) %>%
  anti_join(nations, ., by = c("nation" = "country")) %>%
  filter(year(date) >= 2010) %>%
  {cor.test(.$population_growth, .$gdp_per_capita_growth)}
```

```
