---
title  : "US Rig Counts"
author : "Luke Smith"
date   : "2017-10-06"
tags   : [r, oil, gas, oil and gas, rig counts]
description: ""
twitter :
  card    : "summary_large_image"
  site    : "@lksmth"
  creator : "@lksmth"
  title   : "US Rig Counts"
  description : ""
  image       : ""
og :
  image : ""
---
  
```{r setup_std, include=FALSE, purl=FALSE, eval=TRUE}
# ---- Library_Tidyverse_Setup
library(tidyverse)
library(lubridate)
library(forcats)
library(stringi)

# ---- Library_ploting_Setup
library(grid)
library(gridExtra)
library(ggExtra)
library(GGally)
library(ggalt)
library(scales)
library(extrafont)
loadfonts("win")

# ---- Library_Web_Setup
library(rvest)
library(jsonlite)

# ---- Library_Reporting_Setup
library(knitr)
library(kableExtra)

# ---- My_Blogging_Setup
library(blg)

# ---- Opts_Setup
knitr::opts_chunk$set(echo =  FALSE)
knitr::opts_chunk$set(fig.height = 7)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(purl = FALSE)

# ---- R_Options_Setup
old_scipen <- getOption("scipen")
options(scipen = 100)

old_digits <- getOption("digits")
options(digits = 2)


# ---- knitr_Options_Setup
orig_inline <- knit_hooks$get("inline")
old_plot   <- knit_hooks$get("plot")


# ---- Hooks_Setup

knit_hooks$set(inline = function(x) {
  if (is.numeric(x) | is.integer(x)) return(formatC(x, format = "d", big.mark = ",")) else
    if (is.character(x)) return(stringr::str_to_title(x)) else
      return(x)
})

old_inline <- knit_hooks$get("inline")

my_blue   <- "#0059B3"
my_orange <- "#B35A00"
my_pink   <- "#B30059"
my_green  <- "#59B300"
```

```{r setup_extra, include=FALSE}
library(sf)
library(httr)
library(magick)

theme_set(blg_theme_default())

# Should add to blg package
file_path <- function(..., fsep = .Platform$file.sep) {
  if (length(list(...)) == 0) return(file.path())  
  
  paste0(file.path(..., fsep = fsep), fsep)
}
```



```{r import_from_chunks, eval=TRUE, include=FALSE}
# FROM: us_rig_counts.Rmd
# read_csv_rig_count
# wrangle_data_rig_counts
ref <- "~/R/misc/oil/rig_counts"

# Ref to this working directory
this_dir <- getwd()

# Ref to external code chunks
tmp <- tempdir()
fp <- file.path(tmp, "us_rig_counts.R")
lbls <- c("read_csv_rig_count", "wrangle_data_rig_counts")

knit("us_rig_counts.Rmd", fp, tangle = TRUE)
read_chunk(fp)
```

```{r read_csv_rig_count}
```

```{r wrangle_data_rig_counts}
```



```{r import_og_split, include=FALSE}
ogrc <- file.path(ref, "US Oil & Gas Split.csv") %>%
  read_csv(skip = 6L)
```

```{r tidy_og_split, include=FALSE}
ogrc <- ogrc %>%
  filter(!is.na(Date))

fun_1 <- function(x) stri_replace(x, "", regex = "%$")
fun_2 <- function(x) as.numeric(x) / 100

ogrc <- ogrc %>%
  mutate(Date = as.Date(Date, format = "%m/%d/%Y"),
         `% Oil` = fun_1(`% Oil`),
         `% Oil` = fun_2(`% Oil`),
         `% Gas` = fun_1(`% Gas`),
         `% Gas` = fun_2(`% Gas`))

ogrc <- ogrc %>%
  mutate(Oil = case_when(
    is.na(Oil) ~ as.numeric((Total) - (Gas + Misc)),
    TRUE ~ as.numeric(Oil)
  ))

ogrc <- ogrc %>%
  left_join(oil_prices, by = c("Date" = "date"))

ogrc %>%
  ggplot(aes(Oil, price)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~cut_interval(`% Oil`, 4))
```

```{r quick_funs}
plot_lines <- function(data, dc_order = 1L) {
  is_yearmon <- function(x) identical("yearmon", class(x))
  stopifnot(any(are_date <- purrr::map_lgl(data, ~ lubridate::is.Date(.x) | is_yearmon(.x))))
  
  date_col <- which(are_date)[dc_order]
  
  stopifnot(any(are_numbers <- purrr::map_lgl(data, is.numeric)))
  
  num_cols <- which(are_numbers)
  
  data <- select(data, date_col, num_cols)
  data <- gather(data, ... = -c(date_col))
  
  names(data)[1] <- "date"
  
  gg <- ggplot(data, aes(date, value, group = key)) +
    geom_line() +
    facet_wrap(~key, scales = "free")
  
  return(gg)
}
```


```{r random_plots}
# price ~ Oil
# Faceted by year intervals
ogrc %>%
  ggplot(aes(Oil, price, color = cut_interval(year(Date), 4))) +
  geom_point(alpha = 1/6) +
  geom_smooth(method = "lm", color = blg_colors$blue) +
  facet_wrap(~cut_interval(year(Date), 4)) +
  scale_color_manual(values = c(blg_colors$red, blg_colors$lightred, blg_colors$lightgreen_4, blg_colors$green_4)) +
  guides(color = FALSE)

# price ~ Oil
# Faceted by `% Oil` intervals
ogrc %>%
  filter(year(Date) >= 2007) %>%
  ggplot(aes(Oil, price)) +
  geom_point(aes(color = Date), alpha = 1/2) +
  geom_smooth(method = "lm", color = blg_colors$blue) +
  facet_wrap(~cut_interval(`% Oil`, 4)) +
  guides(color = FALSE)

# Total ~ Oil
# Faceted by `price` intervals
ogrc %>%
  filter(year(Date) >= 2007 & !is.na(price)) %>%
  ggplot(aes(Oil, Total)) +
  geom_point(aes(color = Date), alpha = 1/2) +
  geom_smooth(method = "lm", color = blg_colors$blue) +
  facet_wrap(~cut_interval(`price`, 4)) +
  guides(color = FALSE)
```


```{r ogrc_monthly}
ogrc_m <- ogrc %>%
  select(-`% Oil`, -`% Gas`) %>%
  group_by(Date = zoo::as.yearmon(Date)) %>%
  summarise_all(mean, na.rm = TRUE)
```

```{r join}
stp <- state_prod %>%
  mutate(date = zoo::as.yearmon(date)) %>%
  left_join(ogrc_m, c("date" = "Date"))

# Bye-bye other Alaska's

stp <- stp %>%
  filter(!(location %in% c("Alaska North Slope", "Alaska South"))) %>%
  filter(!grepl("\\(PADD", location))
```

```{r join_plots}
load("~/R/misc/maps/states_map_adjusted.RData")

us_map <- states_map_adjusted %>%
  filter(!(STATE_ABBR == "PR" | STATE_ABBR == "VI") & TYPE == "Land") %>%
  select(-(STATE_FIPS:PRIM_MILES))

stp %>%
  filter(grepl("Texas|North Dakota|Colorado|Oklahoma|California", location)) %>%
  ggplot(aes(production, Oil)) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~location, scales = "free")

stp %>%
  filter(!grepl("U\\.S\\.", location)) %>%
  filter(date >= (max(date) - 10)) %>%
  group_by(location) %>%
  arrange(date) %>%
  mutate(diff = production - production[1]) %>%
  select(location, date, production, diff) %>%
  ungroup() %>%
  ggplot(aes(date, diff, group = location)) +
  geom_line()

# Just US data
us_only <- stp %>%
  filter(grepl("U\\.S\\.", location)) %>%
  filter(date >= (max(date) - 10)) %>%
  arrange(date) %>%
  select(location, date, production) %>%
  spread(location, production) %>%
  mutate(diff_US = U.S. - U.S.[1])

stp %>%
  filter(!grepl("U\\.S\\.", location)) %>%
  filter(date >= (max(date) - 10)) %>%
  left_join(us_only) %>%
  select(-(Oil:price)) %>%
  group_by(location) %>%
  arrange(date) %>%
  mutate(state_percent = production / U.S.,
         diff = production - production[1]) %>%
  ungroup() %>%
  ggplot(aes(date, state_percent, group = location)) +
  geom_line()

stp %>%
  filter(!grepl("U\\.S\\.", location)) %>%
  filter(date >= (max(date) - 10)) %>%
  left_join(us_only) %>%
  select(-(Oil:price)) %>%
  group_by(location) %>%
  arrange(date) %>%
  mutate(state_percent = production / U.S.,
         diff = production - production[1],
         diff_percent = diff / diff_US) %>%
  ungroup() %>%
  select(location, date, state_percent, diff_percent) %>%
  gather(... = -c(location, date)) %>%
  ggplot(aes(date, value, group = location)) +
  geom_line() +
  facet_wrap(~key, scales = "free_y")

# Slope chart
stp %>%
  filter(!grepl("U\\.S\\.", location)) %>%
  filter(date >= (max(date) - 10)) %>%
  left_join(us_only) %>%
  select(-(Oil:price)) %>%
  group_by(location) %>%
  arrange(date) %>%
  mutate(state_percent = production / U.S.,
         diff = production - production[1],
         diff_percent = diff / diff_US) %>%
  ungroup() %>%
  select(location, date, state_percent, diff_percent) %>%
  filter(date == max(date) | date == min(date)) %>%
  mutate(diff_percent = if_else(is.na(diff_percent), 0, diff_percent)) %>%
  gather(... = -c(location, date)) %>%
  ggplot(aes(date, value, group = location)) +
  geom_line() +
  facet_wrap(~key, scales = "free_y")
```

```{r animated_maps}
## Map
us_prod_map <- us_map %>%
  left_join(stp, ., c("location" = "NAME")) %>%
  st_as_sf()

# us_prod_map <- us_map %>%
#   left_join(stp, ., c("location" = "NAME"))

us_prod_map %>%
  ggplot() +
  geom_sf(aes(fill = production))



us_prod_map %>%
  filter(date == max(date) & location != "U.S.") %>%
  mutate(prod_cut = cut(production, breaks = c(0, 10, 60, 180, 800, 2000, 4500), right = FALSE),
         prod_cat = as.integer(prod_cut)) %>%
  select(location:production, prod_cat) %>%
  ggplot() +
  geom_sf(data = us_map, fill = "black") +
  geom_sf(aes(fill = factor(prod_cat))) +
  scale_fill_manual(values = rev(c("black", RColorBrewer::brewer.pal(6, "BrBG"))))


## First animated map
td <- tempdir()

it_date <- us_prod_map %>%
  filter(location != "U.S." & date >= 1981) %>%
  .$date %>%
  unique() %>%
  sort()

img <- map_chr(it_date, ~{
  
  dat <- select(
    filter(
      us_prod_map,
      date == .x & location != "U.S."
    ),
    location:production)
  
  gg <- ggplot(dat) +
    geom_sf(data = us_map) +
    geom_sf(aes(fill = production)) +
    labs(title = paste0("US State Oil Production"),
         subtitle = paste0("Date: ", .x))
  
  fil <- file.path(td, sprintf("%s.png", as.character(.x)))
  ggsave(fil, gg, , units = "in", width=6, height=3.5)
  fil
  
}) %>%
  map(image_read) %>%
  map(image_scale, geometry = "675x") %>%
  image_join()

fin <- img %>%
  image_animate(20) %>%
  image_write("us_map_prod.gif")
```

```{r rc_vs_price, include=FALSE}
comb <- left_join(basin, oil_prices, by = c("Date" = "date"))

ab <- comb %>% filter(key == "Total")
bn <- ab %>% distinct(basin)
bn <- bn %>% union_all(., .)
bn <- bn %>% arrange(basin)
bn_first_basin <- bn %>% slice(1:2)

bn <- bn %>%
  union_all(bn_first_basin) %>%
  mutate(id = row_number())

td <- tempdir()

imgs <- bn$basin %>%
  map2_chr(bn$id, ~{
    gg <- ggplot(filter(ab, basin == .x)) +
      geom_point(aes(value, price, color = Date)) +
      scale_colour_date(low = blg::blg_colors$blue, high = blg::blg_colors$red) +
      # viridis::scale_colour_viridis(option = "A") +
      labs(title = paste0("Rig Count vs Oil Price"),
           subtitle = paste0("Basin: ", .x, "\n"),
           x = "Total Rig Count",
           y = "Oil Price ($)",
           caption = paste0("Source: US EIA; FRED; Baker Hughes")) +
      theme(plot.caption = element_text(size = 10, color = "gray50"))
    
    fil <- file.path(td, sprintf("%s.png", as.character(.y)))
    ggsave(fil, gg, , units = "in", width=6, height=3.5)
    fil
    
  })

imgs <- imgs %>% 
  map(image_read) %>%
  map(image_scale, geometry = "675x")

imgs <- imgs %>%
  image_join()

imgs <- imgs %>% 
  image_animate(10)

imgs <- imgs %>% 
  image_morph(nrow(bn) / 3)

imgs <- imgs %>%
  image_write("rc_vs_price_each.gif")


td <- tempdir()

# Snapshot of each


# Lagging price
ef <- filter(comb, basin == "Eagle Ford" & key == "Total")
wi <- filter(comb, basin == "Williston" & key == "Total")

it <- seq(0L, 16L)

it %>%
  map_chr(~{
    
    gg <- ggplot(ef) +
      geom_point(aes(value, lag(price, .x), color = ef$Date)) +
      labs(title = paste0("Rig count vs Oil price"),
           subtitle = paste0("Price lagged by ", .x, " months"))
    
    fil <- file.path(td, sprintf("%04d.png", as.integer(.x)))
    
    ggsave(fil, gg, , units = "in", width=6, height=3.5)
    
    fil
    
  }) %>% 
  map(image_read) %>%
  map(image_scale, geometry = "675x") %>%
  image_join() %>% 
  image_animate(2) %>% 
  image_write("rc_vs_price_lagged.gif")
```









```{r join_data, include=FALSE, eval=FALSE}
jt <- oil_prices %>%
  group_by(ym = as.yearmon(date)) %>%
  summarise(price = mean(price, na.rm = TRUE)) %>%
  inner_join(trajectory %>%
               group_by(ym = as.yearmon(Date)) %>%
               summarise_at(vars(Directional, Horizontal, Vertical, TOTAL), mean), by = "ym")
```

```{r cleanup, include=FALSE}
rm(list = ls(pattern = "api_key_"))
```
