---
title  : "US Rig Counts"
author : "Luke Smith"
date   : "2017-10-06"
tags   : [r, oil, gas, oil and gas, rig counts]
description: ""
twitter :
  card    : "summary_large_image"
  site    : "@lksmth"
  creator : "@lksmth"
  title   : "US Rig Counts"
  description : ""
  image       : ""
og :
  image : ""
---

```{r setup_std, include=FALSE}
# source("setup_std.R")

# ---- Library_Tidyverse_Setup
library(tidyverse)
library(lubridate)
library(forcats)
library(stringi)

# ---- Library_ploting_Setup
library(grid)
library(gridExtra)
library(ggExtra)
library(GGally)
library(ggalt)
library(scales)
library(extrafont)
loadfonts("win")

# ---- Library_Web_Setup
library(rvest)
library(jsonlite)

# ---- Library_Reporting_Setup
library(knitr)
library(kableExtra)

# ---- My_Blogging_Setup
library(blg)

# ---- Opts_Setup
knitr::opts_chunk$set(echo =  FALSE)
knitr::opts_chunk$set(fig.height = 7)
knitr::opts_chunk$set(message    = FALSE)
knitr::opts_chunk$set(warning    = FALSE)


# ---- R_Options_Setup
old_scipen <- getOption("scipen")
options(scipen = 100)

old_digits <- getOption("digits")
options(digits = 2)


# ---- knitr_Options_Setup
orig_inline <- knit_hooks$get("inline")
old_plot   <- knit_hooks$get("plot")


# ---- Hooks_Setup

knit_hooks$set(inline = function(x) {
  if (is.numeric(x) | is.integer(x)) return(formatC(x, format = "d", big.mark = ",")) else
    if (is.character(x)) return(stringr::str_to_title(x)) else
      return(x)
})

old_inline <- knit_hooks$get("inline")

my_blue   <- "#0059B3"
my_orange <- "#B35A00"
my_pink   <- "#B30059"
my_green  <- "#59B300"
```

```{r setup_extra, include=FALSE}
library(sf)
library(forcats)
library(httr)
library(curl)
library(zeallot)
library(kableExtra)
theme_set(blg_theme_default())
ref <- "~/R/misc/oil/rig_counts"
```


```{r import_oil_price, include=FALSE, eval=FALSE}
api_url <- "https://api.stlouisfed.org/fred/"
req_type <- "series/observations"
req_qry <- "?series_id="
api_qry <- "&api_key="
api_key_fred <- getOption("api_key_fred")
file_type <- "&file_type="

fred_qry <- paste0(api_url, req_type,
                   req_qry, "DCOILWTICO",
                   api_qry, api_key_fred,
                   file_type, "json")

oil_prices <- fred_qry %>%
  read_html() %>%
  html_text() %>%
  fromJSON() %>%
  .[["observations"]] %>%
  as_tibble() %>%
  select(-(1:2))

oil_prices <- oil_prices %>%
  mutate(value = as.double(value),
         date  = as.Date(date)) %>%
  rename(price = value)
```

```{r notes_rig_count, include=FALSE, eval=FALSE}
# Earliest splits by:
#   * Basin      = 2011
#   * State      = 2000
#   * Oil & Gas  = 1987
#   * Trajectory = 1991
#   * GOM        = 2000
#   * Canada (Province)  = 2003
#   * Canada (Oil & Gas) = 2000

# Basin names in rig counts:
# Order        Basin_Name
#     1  Ardmore Woodford
#     2   Arkoma Woodford
#     3           Barnett
#     4     Cana Woodford
#     5       DJ-Niobrara
#     6        Eagle Ford
#     7      Fayetteville
#     8      Granite Wash
#     9       Haynesville
#    10         Marcellus
#    11     Mississippian
#    12           Permian
#    13             Utica
#    14         Williston
#    15            Others
#    16 Total US RigCount
```


```{r fetch_link_rig_count, include=FALSE}
# What an unusual url
url <- "http://phx.corporate-ir.net/phoenix.zhtml?c=79687&p=irol-reportsother"

h <- url %>% read_html()

links <- h %>%
  html_nodes(".ccbnTblLnk")

links_text <- links %>%
  html_text()

which_pivot <- links_text %>%
  grepl("North America Rotary Rig Count Pivot Table \\(Feb 2011 - Current\\) ", .)

which_count <- links_text %>%
  grepl("North America Rotary Rig Count \\(Jan 2000 - Current\\) ", .)


pivot_link <- html_attr(links[which_pivot], "href")
count_link <- html_attr(links[which_count], "href")
```

```{r check_log_exists, include=FALSE, eval=FALSE}
# Get all file names
all_files  <- list.files(ref, full.names = TRUE)

# Find files by extension
xlsb_files <- grepl("\\.xlsb$", all_files)
csv_files  <- grepl("\\.csv$", all_files)
RData_file <- grepl("\\.RData$", all_files)

file_exists <- sum(RData_file)

if (file_exists) {
  
  # Load previous header
  load("~/R/misc/oil/rig_counts/previous_headers.RData")
  
  # Create new folder and move old data
  n_folder <- as.Date(previous_headers[[1]]$date)
  dir.create(paste0(ref, "/", as.character.Date(n_folder)))
    
  # Get files to copy by extension
  files_to_copy <- (xlsb_files | csv_files)
  file.copy(from = all_files[files_to_copy],
            to   = file.path(dirname(all_files[files_to_copy]),
                             n_folder,
                             basename(all_files[files_to_copy])))
  file.remove(all_files[files_to_copy])
  
  }
```

```{r check_for_update_rig_count, include=FALSE, eval=FALSE}
i <- 0L  # counter
start_watch <- Sys.time()

repeat {

  if (!file_exists) break
  if (i == 10L) break
  
  # Send HEAD requests and check headers$`last-modified` against
  # previous headers$`last-modified`
  pivot_req <- HEAD(pivot_link)
  count_req <- HEAD(count_link)

  # FUNCTION: Convert columns to POSIXct
  change_to_POSIXct <- function(x) {
    
    # Get names and find match for likely date-time field
    x_names <- names(x)
    are_date <- grepl("date|last-modified|expires", x_names)
    
    # Convert those which are datetime to POSIXct
    x[are_date] <- map(x[are_date], function(y) {
      y <- as.POSIXct(y,
                      format = "%a, %d %b %Y %H:%M:%S",
                      tz = "GMT")
      attributes(y)$tz <- "America/Chicago"
      return(y)})
    return(x)
  }
  
  # Convert datetime fields to POSIXct
  headers <- map(list(pivot_req$headers, count_req$headers),
                 change_to_POSIXct)
  
  cond <- previous_headers[[1]]$`last-modified` < headers[[1]]$`last-modified` &
      previous_headers[[2]]$`last-modified` < headers[[2]]$`last-modified`
  
    if (cond) {
      previous_headers <- headers
      save(previous_headers,
           file = paste0("~/R/misc/oil/rig_counts/previous_headers.RData"))
      break
    }
  
  # Sys.sleep(30L)
  i <- i + 1L
  
}

exit_watch <- Sys.time()
if (i == 10L) stop(paste0("Data has not been updated.\n",
                            "Started: ", start_watch, "\n",
                            "Exited: ", exit_watch))
```

```{r download_rig_count, include=FALSE, eval=FALSE}
dest_files <- c("pivot.xlsb", "count.xlsb") %>%
  paste0("~/R/misc/oil/rig_counts/", .)

target_files <- c(pivot_link, count_link)

map2(target_files, dest_files, curl_download)
```

```{vbs vbs_script, include=FALSE, eval=FALSE}
x <- c('
Dim xl

Dim fso
Dim dir
Dim File

Dim wb
Dim sh

Set xl = CreateObject("Excel.Application")
Set fso = CreateObject("Scripting.FileSystemObject")
dir = fso.GetAbsolutePathName(".")

With xl
  .Visible = False
  .DisplayAlerts = False
  .AskToUpdateLinks = False
  .AlertBeforeOverwriting = False
  .ScreenUpdating = False
End With

For Each f in fso.GetFolder(dir).Files
  If LCase(fso.GetExtensionName(f.Name)) = "xlsb" Then
    Set wb = xl.Workbooks.Open(f.Path, 0, True)
      For Each sh In wb.Worksheets
        sh.SaveAs dir & "\" & sh.Name & ".csv", 6
      Next
    wb.Close
  End If
Next

xl.Quit

Set wb = Nothing
Set xl = Nothing

WScript.Quit
')

write(x, "~/R/misc/oil/rig_counts/ConvertToCSV.vbs")
```

```{r batch_file, include=FALSE, eval=FALSE}
y <- c('cd C:/Users/Luke/Documents/R/misc/oil/rig_counts
       cscript ConvertToCSV.vbs')

write(y, "~/R/misc/oil/rig_counts/ConvertToCSV.cmd")
```

```{r run_vbs_on_rig_count, include=FALSE, eval=FALSE}
# System command to call a batch file
#   which calls a vbs script
#   which calls an Excel VBA macro
system("C:/Users/Luke/Documents/R/misc/oil/rig_counts/ConvertToCSV.cmd")
```

```{r read_csv_rig_count, include=FALSE}
# ---- Read basin data
# Find and read file; skip first 10
basin_csv <- grep("Basin", list.files(ref, full.names = TRUE), value = TRUE)
basin <- read_csv(basin_csv, skip = 10L)
basin <- basin %>%
  select(-X66) %>% # need to check how many cols and if last is meaningless
  filter(!is.na(Date)) # stupid Excel

# Split by basin and gather variables
basin <- seq.int(2, 65) %>%  # Create seq along columns except `Date`
  split(ceiling(seq_along(.) / 4)) %>%  # Split into groups of 4
  map(~gather(select(basin, 1, .x), ... = -Date))  # Gather the groups of four

# Get names from row 10
basin_names <- read_csv(basin_csv, skip = 9L, n_max = 1L)
basin_names <- names(basin_names)[seq.int(2, length(basin_names) - 1L, 4)]

# Assing to the list element names
names(basin) <- basin_names

# Bind everything by row
basin <- basin %>% bind_rows(.id = "basin")

# ---- Read master data from pivot table
master_csv <- grep("Master Data.csv$", list.files(ref, full.names = TRUE), value = TRUE)
master <- read_csv(master_csv)
```

```{r wrangle_data_rig_counts, include=FALSE}
basin <- basin %>%
  mutate(key = case_when(
    grepl("Oil", key) ~ "Oil",
    grepl("Gas", key) ~ "Gas",
    grepl("Misc", key) ~ "Misc",
    grepl("Total", key) ~ "Total"
    )) %>%
  mutate(Date = as.Date(Date, format = "%m/%d/%Y")) %>%
  filter(basin != "Total US RigCount")

master <- master %>%
  mutate(Basin = if_else(Basin == "Dj-Niobrara", "DJ-Niobrara", Basin),
         PublishDate = stri_replace(PublishDate, "", regex = "\\s+0\\:00"),
         PublishDate = as.Date(PublishDate, format = "%m/%d/%Y"))
```


```{r analyze_data_rig_counts, include=FALSE}
nms <- c("this_week", "week_ago",
         "month_ago", "six_months_ago",
         "year_ago")

key_dates <- basin %>%
    distinct(Date) %>%
    arrange(desc(Date)) %>%
    pull(Date) %>%
    magrittr::extract(c(this_week      = 1,  # magrittr::extract = base::`[`
                        week_ago       = 2,
                        month_ago      = 5,
                        six_months_ago = 27,
                        year_ago       = 53)) %>%
  set_names(nms)

# Find most recent week's change from previous week; Total
totals <- basin %>%
  # mutate(value = as.integer(value)) %>%
  group_by(basin, key) %>%
  arrange(Date) %>%
  mutate(chng_1wk  = (value - lag(value)) / lag(value),
         chng_4wk  = (value - lag(value, 4)) / lag(value, 4),
         chng_16wk = (value - lag(value, 16)) / lag(value, 16),
         chng_52wk = (value - lag(value, 52)) / lag(value, 52)) %>%
  ungroup() %>%
  filter(key == "Total")

c(this_week,
  week_ago,
  month_ago,
  six_months_ago,
  year_ago) %<-% map(nms, ~filter(totals, Date == key_dates[[.x]]))

# Find most recent week's oil and gas type
current_type <- basin %>%
  mutate(value = as.integer(value)) %>%
  group_by(basin, key) %>%
  arrange(Date) %>%
  mutate(chng_1wk = (value - lag(value)) / lag(value),
         chng_4wk = (value - lag(value, 4)) / lag(value, 4),
         chng_16wk = (value - lag(value, 16)) / lag(value, 16),
         chng_52wk = (value - lag(value, 52)) / lag(value, 52)) %>%
  ungroup() %>%
  filter(Date == key_dates[["this_week"]]) %>%
  filter(key != "Total")

current_type <- current_type %>%
    select(basin:value) %>%
    filter(key != "Misc") %>%
    spread(key, value) %>%
    mutate(prcnt_oil = Oil / (Oil + Gas))

# Remove NaN's and NA's for plotting purposes
this_week <- this_week %>%
  mutate_at(vars(chng_1wk, chng_52wk), function(x) if_else(is.na(x), 0, x))

# Create levels vector
tw_levels <- this_week %>%
  arrange(desc(chng_1wk), basin) %>%
  .$basin

# Assign levels
this_week <- this_week %>%
  mutate(basin = factor(basin, levels = tw_levels))

# Weekly summary
summ <- basin %>%
  group_by(key, Date) %>%
  summarize(value = sum(value, na.rm = TRUE))

# ---- Summarize master
# Total rig count by `Year` and `Week`

master_total <- master %>%
  filter(Country == "UNITED STATES") %>%
  group_by(PublishDate, Basin) %>%
  summarize(RigCount = sum(RigCount, na.rm = TRUE)) %>%
  ungroup()

master_total <- master_total %>%
  add_column(Trajectory = "Total")

# Keep only US and remove unneeded columns
master_type <- master %>%
  filter(Country == "UNITED STATES") %>%
  select(-Country, -WellDepth, -(Year:Week))

# Group and summarize
master_type <- master_type %>%
  group_by(Basin, Trajectory, PublishDate) %>%
  summarize(RigCount = sum(RigCount, na.rm = TRUE)) %>%
  ungroup()

master_type <- master_type %>%
    union_all(master_total) %>%
    spread(Trajectory, RigCount) %>%
    mutate(hz = Horizontal / Total)

diff <- basin %>%
    filter(Date == key_dates[["this_week"]] | Date == key_dates[["week_ago"]]) %>%
    filter(key != "Total") %>%
  group_by(Date, key) %>%
  arrange(Date) %>%
  summarize(value = sum(value)) %>%
  ungroup() %>%
    spread(key, value)

diff <- diff %>%
  rowwise() %>%
  mutate(Total = sum(Gas, Misc, Oil))
```

```{r print_diff}
diff %>%
  kable(format = "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover"),
                full_width = FALSE)
```


```{r import_sf_data, include=FALSE}
sf_plays_orig <- st_read("~/R/misc/oil/US/eia_shape/TightOil_ShaleGas_Plays_Lower48_EIA/TightOil_ShalePlays_US_EIA_May2016.shp")

sf_basins <- st_read("~/R/misc/oil/US/eia_shape/SedimentaryBasins_US_EIA/SedimentaryBasins_US_May2011_v2.shp")

load("~/R/misc/maps/states_map.RData")
```

```{r import_drawn_mapedit_data, include=FALSE}
# These two had to be "hand-drawn" using the mapedit package

granite_wash <- structure(list(Basin = "Granite Wash", feature_type = "polygon", 
    geometry = structure(list(structure(list(structure(c(-99.9976, 
    -100.2063, -100.3436, -100.5469, -100.6787, -100.8435, -100.8545, 
    -100.8215, -100.6787, -100.5029, -100.3079, -100.1129, -99.7229, 
    -99.4263, -99.2725, -99.1296, -99.0088, -98.9978, -99.1516, 
    -99.3823, -99.4592, -99.5581, -99.7339, -99.9976, 35.7733, 
    35.8623, 35.9202, 36.0313, 36.0757, 36.0846, 35.9869, 35.9157, 
    35.8089, 35.6751, 35.5412, 35.407, 35.1379, 35.021, 34.976, 
    34.976, 34.976, 35.084, 35.1828, 35.2815, 35.3532, 35.4338, 
    35.5859, 35.7733), .Dim = c(24L, 2L))), class = c("XY", "POLYGON", 
    "sfg"))), n_empty = 0L, precision = 0, class = c("sfc_POLYGON", 
    "sfc"), bbox = structure(c(-100.8545, 34.976, -98.9978, 36.0846
    ), .Names = c("xmin", "ymin", "xmax", "ymax"), class = "bbox"), crs = structure(list(
        epsg = 4326L, proj4string = "+proj=longlat +datum=WGS84 +no_defs"), .Names = c("epsg", 
    "proj4string"), class = "crs")), Lithology = NA, Shale_play = "Granite Wash", 
    Source = "Hand Drawn", Area_sq_mi = NA, Area_sq_km = NA, 
    Age_shale = NA), row.names = c(NA, -1L), class = c("sf", 
"data.frame"), sf_column = "geometry", agr = structure(c(NA_integer_, 
NA_integer_), class = "factor", .Label = c("constant", "aggregate", 
"identity"), .Names = c("Basin", "feature_type")), .Names = c("Basin", 
"feature_type", "geometry", "Lithology", "Shale_play", "Source", 
"Area_sq_mi", "Area_sq_km", "Age_shale"))

mississippian <- structure(list(Basin = "Mississippian", feature_type = "polygon", 
    geometry = structure(list(structure(list(structure(c(-98.5474, 
    -99.0747, -99.4263, -99.5142, -99.2285, -98.6572, -97.4268, 
    -96.5918, -96.1523, -95.8887, -95.6909, -95.5151, -95.6909, 
    -96.1084, -97.0752, -97.7563, -98.5474, 36.3151, 36.4213, 
    36.6155, 37.0201, 37.2653, 37.3178, 37.4225, 37.3352, 37.1778, 
    37.1078, 36.9499, 36.6684, 36.3505, 36.2088, 36.2266, 36.2974, 
    36.3151), .Dim = c(17L, 2L))), class = c("XY", "POLYGON", 
    "sfg"))), n_empty = 0L, precision = 0, class = c("sfc_POLYGON", 
    "sfc"), bbox = structure(c(-99.5142, 36.2088, -95.5151, 37.4225
    ), .Names = c("xmin", "ymin", "xmax", "ymax"), class = "bbox"), crs = structure(list(
        epsg = 4326L, proj4string = "+proj=longlat +datum=WGS84 +no_defs"), .Names = c("epsg", 
    "proj4string"), class = "crs")), Lithology = NA, Shale_play = "Mississippian", 
    Source = "Hand Drawn", Area_sq_mi = NA, Area_sq_km = NA, 
    Age_shale = NA), row.names = c(NA, -1L), class = c("sf", 
"data.frame"), sf_column = "geometry", agr = structure(c(NA_integer_, 
NA_integer_), class = "factor", .Label = c("constant", "aggregate", 
"identity"), .Names = c("Basin", "feature_type")), .Names = c("Basin", 
"feature_type", "geometry", "Lithology", "Shale_play", "Source", 
"Area_sq_mi", "Area_sq_km", "Age_shale"))
```


```{r wrangle_sf_data, include=FALSE}
states_48 <- states_map %>%
  filter(NAME %in% c(state.name, "District of Columbia")) %>%
  filter(!(NAME %in% c("Alaska", "Hawaii"))) %>%
  filter(TYPE != "Water")

sf_plays <- sf_plays_orig %>%
  filter(Shale_play != "Heath") %>%
    mutate(Shale_play = case_when(
      Basin == "Ardmore"  ~ "Ardmore Woodford",
      Basin == "Arkoma" & Shale_play != "Fayetteville"  ~ "Arkoma Woodford",
      Basin == "Anadarko" ~ "Cana Woodford",
      Basin == "Williston" ~ "Williston",
      Basin == "Permian" ~ "Permian",
      Basin == "Denver Basin" ~ "DJ-Niobrara",
      Basin == "TX-LA-MS Salt Basin" ~ "Haynesville",
      TRUE ~ as.character(Shale_play)
    ))

granite_wash <- granite_wash %>%
  select(-feature_type) %>%
  st_cast("MULTIPOLYGON")
mississippian <- mississippian %>%
  select(-feature_type) %>%
  st_cast("MULTIPOLYGON")

sf_plays <- sf_plays %>%
  rbind(granite_wash) %>%
  rbind(mississippian) %>%
  filter(Shale_play %in% this_week$basin)

# ---- Merge MULTIPOLYGONS
# Split and union (i.e. dissolve/merge) multi's
new_geometry <- sf_plays %>%
  split(.$Shale_play) %>%
  magrittr::extract(unlist(lapply(., function(x) nrow(x) > 1))) %>%
  map(~st_cast(st_sf(st_union(.x)), "MULTIPOLYGON")) %>%
  reduce(rbind)

# Get rid of duplicates
grouped_sf_plays <- sf_plays %>% group_by(Shale_play)
new_sf_plays <- grouped_sf_plays %>% filter(!(n() > 1))
dupe_sf_plays <- grouped_sf_plays %>% filter(n() > 1) %>% slice(c(1, nrow(.)))

st_geometry(dupe_sf_plays) <- st_geometry(new_geometry)
sf_plays <- new_sf_plays %>%
  rbind(dupe_sf_plays)

# ---- Create text table for `geom_text()`
# Find centroid of each feature to use as (x, y) for text
sf_text <- sf_plays %>%
  st_centroid()

# Extract coordinates
sf_text <- sf_text %>%
  st_coordinates() %>%
  cbind(as_tibble(sf_text), .)

tst <- sf_text %>%
  cbind(tibble(offset_X = c( 5.8,  1.7, # Ardmore,      Fayetteville
                             3.5,  5.4, # Barnett,      Arkoma
                            -5.6,  2.0, # Cana,         Haynesville
                            -4.8,       # Eagle Ford
                            -4.5, -5.7, # DJ-Niobrara, Marcellus
                            -5.4, -4.1, # Utica, Granite Wash
                             0.0, -3.8, # Mississippian, Permian
                            -3.7))) %>% # Williston
  cbind(tibble(offset_Y = c(-0.8,  0.9, # Ardmore,      Fayetteville
                            -0.87, -0.5, # Barnett,      Arkoma
                             1.1,  0.0, # Cana,  Haynesville
                            -0.5,       # Eagle Ford
                            -1.0, -2.7, # DJ-Niobrara, Marcellus
                             0.0,  0.0, # Utica, Granite Wash
                             1.5,  1.0, # Mississippian, Permian
                            -1.0))) %>% # Williston
  mutate(X = X + offset_X,
         Y = Y + offset_Y)

tst_proj <- tst %>%
    mutate(new_X = X + offset_X,
           new_Y = Y + offset_Y,

           new_X = case_when(
             Shale_play == "Ardmore Woodford" ~ new_X * 1.072, #$ + pos
             Shale_play == "Fayetteville" ~ new_X * 1.03,      #$ + pos
             Shale_play == "Barnett" ~ new_X * 1.05,           #$ + pos
             Shale_play == "Arkoma Woodford" ~ new_X * 1.07,   #$ + pos
             Shale_play == "Cana Woodford" ~ new_X * 0.95,     #$ - neg
             Shale_play == "Haynesville"   ~ new_X * 1.00,
             Shale_play == "Eagle Ford" ~ new_X * 0.955,       #$ - neg
             Shale_play == "DJ-Niobrara" ~ new_X * 0.96,       #$ - neg
             Shale_play == "Marcellus" ~ new_X * 0.94,         #$ - neg
             Shale_play == "Utica" ~ new_X * 0.935,            #$ - neg
             Shale_play == "Granite Wash" ~ new_X * 0.96,      #$ - neg
             Shale_play == "Mississippian" ~ new_X * 1.00,     #$ 0
             Shale_play == "Permian" ~ new_X * 0.9675,         #$ - neg
             Shale_play == "Williston" ~ new_X * 0.985         #$ - neg
             ),
           new_Y = case_when(
             Shale_play == "Ardmore Woodford" ~ new_Y * 1.038, #$ - neg
             Shale_play == "Fayetteville" ~ new_Y * 0.975,     #$ + pos
             Shale_play == "Barnett" ~ new_Y * 1.00,           #$ - neg
             Shale_play == "Arkoma Woodford" ~ new_Y * 1.02,   #$ - neg
             Shale_play == "Cana Woodford" ~ new_Y * 0.97,     #$ + pos
             Shale_play == "Haynesville"   ~ new_Y * 1.00,
             Shale_play == "Eagle Ford" ~ new_Y * 1.035,       #$ - neg
             Shale_play == "DJ-Niobrara" ~ new_Y * 1.04,       #$ - neg
             Shale_play == "Marcellus" ~ new_Y * 1.079,        #$ - neg
             Shale_play == "Utica" ~ new_Y * 1.00,             #$ 0
             Shale_play == "Granite Wash" ~ new_Y * 1.00,      #$ 0
             Shale_play == "Mississippian" ~ new_Y * 0.96,     #$ + pos
             Shale_play == "Permian" ~ new_Y * 0.95,           #$ 0
             Shale_play == "Williston" ~ new_Y * 1.05          #$ - neg
             )) %>%
    st_as_sf(coords = c("new_X", "new_Y"), crs = 4326, agr = "identity") %>%
    st_transform(102003)

tst_proj <- tst_proj %>%
    select(-(X:Y)) %>%
    st_coordinates() %>%
    cbind(as_tibble(tst_proj %>% select(-(X:Y))), .)

# ---- Merge datasets with sf data
sf_plays_total <- sf_plays %>%
  merge(this_week, by.x = "Shale_play", by.y = "basin")

sf_current_type <- sf_plays %>%
  merge(current_type, by.x = "Shale_play", by.y = "basin")
```

```{r join_data, include=FALSE, eval=FALSE}
jt <- oil_prices %>%
    group_by(ym = as.yearmon(date)) %>%
    summarise(price = mean(price, na.rm = TRUE)) %>%
    inner_join(trajectory %>%
                   group_by(ym = as.yearmon(Date)) %>%
                   summarise_at(vars(Directional, Horizontal, Vertical, TOTAL), mean), by = "ym")
```


```{r plot_rig_count, fig.height=9.2}
# Create blank geom to hold plots
gb <- ggplot() +
  geom_blank() +
  labs(title = "Rigging up, rigging down",
       subtitle = paste0("Where did rig counts change from the week of ", key_dates[["week_ago"]], " to\n",
                         key_dates[["this_week"]], "?")) +
  theme(axis.title = element_blank()) +
  theme(plot.caption = element_text("Open Sans", colour = "gray30", size = 12))

# ---- Map
wk1_colors <- this_week$chng_1wk %>%
  sign() %>%
  unique()

map_colors <- switch(as.character(sum(wk1_colors + c(2, 4, 6))),
       "2" = blg_colors$red,
       "3" = "gray50",
       "5" = c(blg_colors$red, "gray50"),
       "7" = blg_colors$blue,
       "9" = c(blg_colors$red, blg_colors$blue),
       "10" = c("gray50", blg_colors$blue),
       "12" = c(blg_colors$red, "gray50", blg_colors$blue))

rc_map <- sf_plays_total %>%
  ggplot() +
  geom_sf(data = states_48, fill = "white", color = "gray60") +
  geom_sf(aes(fill = factor(sign(chng_1wk))),
          color = "black",
          alpha = 0.9) +
  geom_text(data = tst_proj, aes(X, Y, label = Shale_play), size = 3) +
  scale_fill_manual(name = NULL,
                    values = map_colors,
                    labels = c("Decrease", "No Change", "Increase")) +
  coord_sf(crs = st_crs(102003), datum = NA) +
  guides(color = FALSE,
         alpha = FALSE) +
  theme(axis.title = element_blank()) +
  theme(plot.caption = element_text("Open Sans", colour = "gray30", size = 12),
        legend.position = c(0.85, 0.08),
        legend.justification = c("left", "bottom"),
        legend.box.just = "right")

# ---- Change from week ago
  # Create levels vector
    chng_1wk_levels <- this_week %>%
      arrange(desc(chng_1wk), basin) %>%
      .$basin
  
  # Assign levels
  this_week <- this_week %>%
    mutate(basin = factor(basin, levels = chng_1wk_levels))
  
wk1_colors <- switch(as.character(sum(wk1_colors) + 2),
                    "1" =  blg_colors$red, # when only negative change
                    "2" =  c(blg_colors$blue, blg_colors$red), # when both
                    "3" =  blg_colors$blue) # when only positive change

# ---- BAR - Change from week ago; rig count
rc_chng_1wk <- this_week %>%
  filter(chng_1wk != 0 & !is.infinite(chng_52wk)) %>%
  ggplot() +
  geom_col(aes(fct_rev(basin), chng_1wk, fill = chng_1wk < 0)) +
  coord_flip() +
  scale_fill_manual(values = wk1_colors) +
  scale_y_continuous(labels = blg_frmt_percent(0),
                     # breaks = c(-0.10, 0, 0.10, 0.20),
                     minor_breaks = NULL) +
  guides(fill = FALSE) +
  labs(title = "Percent change from\nprevious week",
       x = NULL,
       y = NULL) +
  blg_theme_default(12)

# ---- Change from year ago
  # Create levels vector
  chng_52wk_levels <- this_week %>%
    arrange(desc(chng_52wk), basin) %>%
    .$basin
  
  # Assign levels
  this_week <- this_week %>%
    mutate(basin = factor(basin, levels = chng_52wk_levels))

wk52_colors <- this_week$chng_52wk %>%
  sign() %>%
  unique()

wk52_colors <- switch(as.character(sum(wk52_colors) + 2),
                      "1" = blg_colors$red, # when only negative change
                      "2" = c(blg_colors$blue, blg_colors$red), # when both
                      "3" = blg_colors$blue) # when only positive change

# ---- BAR - Rig count; 52 week percent change
rc_chng_52wk <- this_week %>%
  filter(chng_52wk != 0 & !is.infinite(chng_52wk)) %>%
  ggplot() +
  geom_col(aes(fct_rev(basin), chng_52wk, fill = chng_52wk < 0)) +
  coord_flip() +
  scale_fill_manual(values = wk52_colors) +
  scale_y_continuous(labels = blg_frmt_percent(0)) +
  guides(fill = FALSE) +
  labs(title = "Percent change from\nprevious year",
       x = NULL,
       y = NULL) +
  blg_theme_default(12)


# ---- BAR - Total current rig total
rc_total <- this_week %>%
  arrange(value) %>%
  mutate(basin = factor(basin, levels = basin)) %>%
  ggplot() +
  geom_col(aes(basin, value), fill = blg_colors$green) +
  labs(title = "\nTotal rig count",
       x = NULL,
       y = NULL) +
  blg_theme_default(12) +
  rotateTextX(30, vjust = 1)

# ---- GROBS
rc_grobs <- arrangeGrob(rc_map, rc_chng_1wk, rc_chng_52wk,
                        layout_matrix = rbind(c(1, 1),
                                              c(2, 3)))

gb_grob <- ggplotGrob(gb)
gb_grob$grobs[[which(gb_grob$layout$name == "panel")]] <- gb_grob$grobs[[which(gb_grob$layout$name == "panel")]] %>%
  addGrob(rc_grobs)

grid.draw(gb_grob)
```

```{r plot_rig_type, fig.height=9.2}
# ---- LAYOUT - Rig type
gb <- ggplot() +
  geom_blank() +
  labs(title = "Focal point",
       subtitle = paste0("Which resource are rigs after for the week of ", key_dates[["this_week"]], "?")) +
  theme(axis.title = element_blank()) +
  theme(plot.caption = element_text("Open Sans", colour = "gray30", size = 12))

# ---- LINE - Rig type
summ_text <- summ %>%
    ungroup() %>%
    filter(key != "Misc") %>%
    mutate(Date = as.Date(Date)) %>%
    group_by(key) %>%
    arrange(desc(Date)) %>%
    filter(row_number() == 1) %>%
    ungroup() %>%
    mutate(label_key = stri_pad_right(key, max(stri_length(key))),
           label_value = stri_pad_right(paste0("(", comma(value), ")"),
                                        max(stri_length(paste0("(", comma(value), ")")))),
           label = paste0(label_key, "\n", label_value))

summ_text <- summ_text %>%
  mutate(x = Date + 100,
         y = case_when(
           key == "Total" ~ value + 20,
           key == "Oil"   ~ value - 110,
           key == "Gas"   ~ value + 15
         ))

# summ_text$x <- summ_text$Date + 100
# summ_text$y <- summ_text$value + c(10, -50, 50)

rt_type <- summ %>%
  filter(key != "Misc") %>%
  mutate(Date = as.Date(Date)) %>%
  ggplot() +
  geom_line(aes(Date, value, color = key), size = 0.7) +
  geom_text(aes(x, y, group = key, color = key, label = label),
            summ_text) +
  scale_y_continuous(labels = comma) +
  scale_color_manual(values = c(
    # "#004A94",
    "#01665E",
    # "#004A94",
    "#8C510A",
    "black")) +
  guides(color = FALSE) +
  labs(title = "Rig count by well type",
       y = "Rig count") +
  blg_theme_default(12)

# ---- MAP - Rig type
rt_map <- sf_current_type %>%
  ggplot() +
  geom_sf(data = states_48, fill = "white", color = "gray60") +
  geom_sf(aes(fill = prcnt_oil),
          color = "black",
          alpha = 0.9) +
  geom_text(data = tst_proj, aes(X, Y, label = Shale_play), size = 3) +
  scale_fill_gradient2(name = NULL,
                       # low = "#004A94",
                       low = "#01665E",
                       mid = "#F5F5F5",
                       # high = "#940100",
                       high = "#8C510A",
                       midpoint = 0.5,
                       na.value = "gray50",
                       labels = c("100% Gas", "", "Split", "", "100% Oil")) +
  coord_sf(crs = st_crs(102003), datum = NA) +
  guides(alpha = FALSE) +
  theme(axis.title = element_blank()) +
  theme(plot.caption = element_text("Open Sans", colour = "gray30", size = 12),
        legend.position = c(0.85, 0.08),
        legend.justification = c("left", "bottom"),
        legend.box.just = "right")

gb_grob <- ggplotGrob(gb)

rt_grobs <- arrangeGrob(rt_map, rt_type, layout_matrix = rbind(c(2, 2),
                                                               c(1, 1)))

gb_grob$grobs[[which(gb_grob$layout$name == "panel")]] <- gb_grob$grobs[[which(gb_grob$layout$name == "panel")]] %>%
  addGrob(rt_grobs)

grid.draw(gb_grob)
```

```{r plot_numbers_summary, include=FALSE, eval=FALSE}
x <- week_ago %>% bind_rows(this_week) %>%
  mutate(Date = as.factor(Date)) %>%
  group_by(key) %>%
  summarize(value = sum(value)) %>%
  ungroup()

y <- year_ago %>% bind_rows(this_week) %>%
  mutate(Date = as.factor(Date)) %>%
  group_by(key) %>%
  summarize(value = sum(value)) %>%
  ungroup()

x %>%
  ggplot(aes(Date, value, group = basin)) +
  geom_line() +
  geom_line(data = y,
            aes(Date, value, group = basin)) +
  geom_point(size = 1) +
  geom_point(data = y,
             aes(Date, value, group = basin),
             size = 1)
```

```{r exp, include=FALSE, eval=FALSE}
ckey <- basin %>%
  group_by(basin, key) %>%
  arrange(Date) %>%
  mutate(chng_1wk = (value - lag(value)) / value,
         chng_4wk = (value - lag(value, 4)) / value,
         chng_16wk = (value - lag(value, 16)) / value,
         chng_52wk = (value - lag(value, 52)) / value) %>%
  ungroup() %>%
  filter(Date == key_dates[["this_week"]]) %>%
  filter(key != "Total")

ckey <- ckey %>%
  mutate(basin = factor(basin, levels = tw_levels))

ckey <- ckey %>%
  mutate(chng_1wk = if_else(is.na(chng_1wk), 0, chng_1wk))

ckey %>%
  select(basin:chng_1wk) %>%
  spread(key, value) %>%
  filter(chng_1wk != 0)
```

```{r tween_prep, include=FALSE, eval=FALSE}
# ----
# GIF
# ----

# tweenr
library(tweenr)

# Need the right variables
t <- master_type %>%
  select(Basin, PublishDate, hz) %>%
  rename(x = PublishDate, y = hz, id = Basin)

# Need to ensure that all dates appear in each split
unique_dates <- t %>% distinct(x)

# tweenr will not accept missing rows (missing dates in this case)
t <- t %>%
  split(.$id) %>%
  map(function(x) {
    missing_dates <- anti_join(unique_dates, x)
    if (nrow(missing_dates) > 0) {
        x <- add_row(x,
                     id = x$id[1],
                     x  = missing_dates$x,
                     y  = rep(0, nrow(missing_dates)))
    }
    return(x)
    }) %>%
  bind_rows()

# NA's suck...in this case.
#   How did they even happen?
t <- t %>%
  mutate(y = if_else(is.na(y), 0, y))

# tween_states needs a list of data frames
#   and to make a repeating loop we need
#   to mesh the beginning and the end (
#   by repeating the beginning at the end)
t <- t %>%
  split(.$id) %>%
  c(.[1])

# Rows must be in order to be properly
#   interpolated.
t <- t %>%
  map(arrange, x)


# Non-numerics need to be protected
#   by converting to factor
t <- t %>%
  map(~mutate(.x,
              id = as.factor(id),
              x  = as.factor(x))
      )
```

```{r tween_exec, include=FALSE, eval=FALSE}
t_tween <- t %>%
  tween_states(1, 0.7, "cubic-in-out", 200) %>%
  as_tibble()

t_tween <- t_tween %>%
  mutate(id = as.character(id),
         x  = as.Date(x))
```

```{r plot_tweenr_hz, include=FALSE, eval=FALSE}
library(magick)
td <- tempdir()

  
map_chr(unique(t_tween$.frame), ~{
  
  
  d <- filter(t_tween, .frame == .x)
  gg <- ggplot(d, aes(frame = .frame)) +
    geom_line(aes(x, y)) +
    labs(title = paste0("Horizontal-rig makeup of various US",
                        "\noil and gas basins."),
         subtitle = paste0("Basin: ", unique(d$id), "\n"),
         x = paste0("Date"),
         y = paste0("Percent horizontal (%)"),
         caption = paste0("Source: Baker Hughes Rig Count")) +
    scale_y_continuous(breaks = c(0, 0.25, 0.5, 0.75, 1.0),
                       limits = c(0, 1),
                       labels = blg_frmt_percent(0)) +
    scale_x_date(limits = c(as.Date("2011-01-01"), as.Date("2018-04-01"))) +
    theme(axis.title.y = element_text(size = 12),
          plot.caption = element_text(size = 10, color = "gray50"))
  
  fil <- file.path(td, sprintf("%04d.png", as.integer(.x)))

  ggsave(fil, gg, , units = "in", width=6, height=3.5)
  
  fil
  
}) %>% 
  map(image_read) %>%
  map(image_scale, geometry = "675x") %>%
  image_join() %>% 
  image_animate() %>% 
  image_write("animated.gif")
```

```{r plot_tweenr_type, include=FALSE, eval=FALSE}
td <- tempdir()

map_chr(unique(summ_animate$Date), ~{
    d <- filter(summ_animate, Date == .x)
    gg <- ggplot(d) +
        geom_line(aes(Date, value, color = key), size = 0.7) +
        geom_text(aes(x, y, group = key, color = key, label = label),
                  summ_text) +
        scale_x_date(limits = c(as.Date("2011-01-01"), as.Date("2018-04-01"))) +
        scale_y_continuous(limits = c(0, 2100),
                           labels = comma) +
        scale_color_manual(values = c(
            # "#004A94",
            "#01665E",
            # "#004A94",
            "#8C510A",
            "black")) +
        guides(color = FALSE) +
        labs(title = "Rig count by well type",
             y = "Rig count") +
        blg_theme_default(12)
    
    fil <- file.path(td, sprintf("%04d.png", as.integer(.x)))
    
    ggsave(fil, gg, , units = "in", width=6, height=3.5)
    
    fil
    
}) %>%
    map(image_read) %>%
    map(image_scale, geometry = "675x") %>%
    image_join() %>%
    image_animate() %>%
    image_write("rig_count_animate.gif")
```

```{r exp_plot, include=FALSE, eval=FALSE}
# ---- OLDER
t <- master_type %>%
  select(Basin, PublishDate, hz)

# NEED TO SPLIT BY `PublishDate` NOT `id`!!!
t_tween <- t %>%
  rename(x = PublishDate, y = hz, id = Basin) %>%
  mutate(id = factor(id)) %>%
  group_by(id) %>%
  nest()


t_tween <- t %>%
  rename(x = PublishDate, y = hz, id = Basin) %>%
  mutate(id = factor(id)) %>%
  group_by(id) %>%
  nest()

# t_tween <- t_tween %>%
#     mutate(PublishDate = x, Basin = id) %>%
#     inner_join(t)

# ggplot2
p <- ggplot(t_tween, aes(id, y, frame = .frame)) +
    geom_point()

# gganimate
library(gganimate)
gganimate(p)

# ---- Other
this_week %>%
  ggplot() +
  geom_point(aes(fct_rev(basin), chng_1wk, color = factor(sign(chng_1wk)), size = value)) +
  geom_segment(aes(x = basin, xend = basin, y = 0, yend = chng_1wk, color = factor(sign(chng_1wk)))) +
  coord_flip() +
  scale_color_manual(name = "Change",
                     values = c(blg_colors$red, "black", blg_colors$blue)) +
  scale_size_continuous(name = "Number of rigs") +
  scale_y_continuous(labels = blg_frmt_percent(1),
                     limits = c(-0.05, 0.05),
                     breaks = c(-0.05, -0.025, 0, 0.025, 0.05)
                     ) +
  guides(color = FALSE) +
  labs(title = "US rig count (lower 48 states)",
       subtitle = paste0("Percent change in rig count from week of\n",
                         key_dates[["week_ago"]], " to ", key_dates[["this_week"]]),
       x = paste0("Basin"),
       y = paste0("Percent change in rigs")) +
  blg_theme_default(14)
```

```{r map_conversion, include=FALSE, eval=FALSE}
gj_plays_total <- geojson_json(sf_plays_total)
gj_states_48 <- geojson_json(states_48 %>% st_transform(4326))
```
