---
title  : "US Rig Counts: Counties"
author : "Luke Smith"
date   : "2017-10-06"
tags   : [r, oil, gas, oil and gas, rig counts]
description: ""
twitter :
  card    : "summary_large_image"
  site    : "@lksmth"
  creator : "@lksmth"
  title   : "US Rig Counts"
  description : ""
  image       : ""
og :
  image : ""
---

```{r setup_lib_std, include=FALSE}
# ---- Library_Tidyverse_Setup
library(tidyverse)
library(lubridate)
library(forcats)
library(stringi)

# ---- Library_ploting_Setup
library(grid)
library(gridExtra)
library(ggExtra)
library(GGally)
library(ggalt)
library(scales)
library(extrafont)

# ---- Library_Web_Setup
library(rvest)
library(jsonlite)

# ---- Library_Reporting_Setup
library(knitr)
library(kableExtra)

# ---- My_Blogging_Setup
library(blg)
```

```{r knitr_opts_chunk_std, include=FALSE}
# ---- Opts_Setup
knitr::opts_chunk$set(echo =  FALSE)
knitr::opts_chunk$set(fig.height = 7)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r knitr_opts_hooks_std, include=FALSE}
# ---- knitr_Options_Setup
orig_inline <- knit_hooks$get("inline")
old_plot   <- knit_hooks$get("plot")

# ---- Hooks_Setup
knit_hooks$set(inline = function(x) {
  if (is.numeric(x) | is.integer(x)) return(formatC(x, format = "d", big.mark = ",")) else
    if (is.character(x)) return(stringr::str_to_title(x)) else
      return(x)
})

old_inline <- knit_hooks$get("inline")
```

```{r r_opts_std, include=FALSE}
# ---- R_Options_Setup
old_scipen <- getOption("scipen")
options(scipen = 100)

old_digits <- getOption("digits")
options(digits = 2)
```

```{r r_misc_std, include=FALSE}
loadfonts("win")

my_blue   <- "#0059B3"
my_orange <- "#B35A00"
my_pink   <- "#B30059"
my_green  <- "#59B300"
```

<!-- Extra setup -->

```{r setup_lib_extra, include=FALSE}
library(sf)
library(httr)
library(magick)
library(geojsonio)
```

```{r r_misc_extra, include=FALSE}
theme_set(blg_theme_default())
```

<!-- Load data -->

```{r load_data, include=FALSE}
ref1 <- "~/R/misc/oil/US/rig_counts"
ref2 <- "~/R/misc/maps"

# Rig count - master
load(file.path(ref1, "rc_master.RData"))

# US counties map (Albers projection)
load(file.path(ref2, "counties_2014_adjusted.RData"))

# US states map (Albers projection)
load("~/R/misc/maps/states_map_adjusted.RData")
```

```{r tidy_rc_master, include=FALSE}
rc_master <- rc_master %>%
    mutate(County = str_replace(County, "^ST\\.", "SAINT"),
           County = str_replace(County, "DE WITT", "DEWITT"))
```

```{r tidy_counties_2014_adjusted, include=FALSE}
counties_2014_adjusted <- counties_2014_adjusted %>%
  filter(!(STATE == "PR" | STATE == "VI")) %>%
  filter(!is.na(NAME)) %>%
  left_join(state_lookup, c("STATE" = "state_abb")) %>%
  mutate_at(vars(state_name, NAME), toupper)
```

```{r tidy_states_map_adjusted}
us_map <- states_map_adjusted %>%
  filter(!(STATE_ABBR == "PR" | STATE_ABBR == "VI") & TYPE == "Land") %>%
  select(-(STATE_FIPS:PRIM_MILES))
```
<!-- Pre-Analysis Checks -->

```{r checks, include=FALSE}
## Do all rig count counties match a corresponding
#  county in the map?
no_join_check <- rc_master %>%
  filter(Location == "Land") %>%
  filter(Country == "UNITED STATES") %>%
  filter(PublishDate == max(PublishDate)) %>%
  group_by(`State/Province`, County) %>%
  summarize(n = n()) %>%
  ungroup() %>%
  anti_join(counties_2014_adjusted, c("County" = "NAME", "State/Province" = "state_name"))
```

<!-- Analysis -->

```{r current_week_location}
rc_master %>%
  filter(PublishDate == max(PublishDate)) %>%
  inner_join(counties_2014_adjusted, c("County" = "NAME", "State/Province" = "state_name")) %>%
  ggplot() +
  geom_sf(data = counties_2014_adjusted, color = "black", fill = "gray40") +
  geom_sf(aes(fill = "1"), color = "black") +
  coord_sf(datum = NA) +
  scale_fill_manual(values = clrs$orange) +
  labs(title = paste0("US counties where an oil or gas rig is located"),
       subtitle = paste0("For the week of ", max(rc_master$PublishDate))) +
  guides(fill = FALSE)
```

```{r rig_type}
## Plot each
rig_type_each <- rc_master %>%
    filter(Location == "Land") %>%
    filter(Country == "UNITED STATES") %>%
    filter(PublishDate == max(PublishDate)) %>%
    group_by(`State/Province`, County, DrillFor) %>%
    summarize(n = n()) %>%
    ungroup()

rig_type_both <- rc_master %>%
  filter(Location == "Land") %>%
  filter(Country == "UNITED STATES") %>%
  filter(PublishDate == max(PublishDate)) %>%
  group_by(`State/Province`, County, DrillFor) %>%
  summarize(n = n()) %>%
  ungroup() %>%
  group_by(`State/Province`, County) %>%
  filter(n() > 1 & row_number() == 1) %>%
  ungroup() %>%
  mutate(DrillFor = "Both")

if (nrow(no_join_check) == 0) {
  
rig_type_each %>%
    anti_join(rig_type_both, c("State/Province", "County")) %>%
    bind_rows(rig_type_both) %>%
    left_join(counties_2014_adjusted, c("County" = "NAME", "State/Province" = "state_name")) %>%
    st_as_sf() %>%
    ggplot() +
    geom_sf(data = counties_2014_adjusted,
            color = "gray40", fill = "gray40") +
    geom_sf(aes(fill = factor(DrillFor, levels = c("Oil", "Gas", "Both"))), color = "black") +
    coord_sf(datum = NA) +
    labs(title = paste0("US counties where an oil or gas rig is located"),
         subtitle = paste0("For the week of ", max(rc_master$PublishDate))) +
    scale_fill_manual("Rig type:", values = c(clrs$red, clrs$blue, clrs$purple)) +
    theme(axis.title = element_blank(),
          axis.text = element_blank(),
          legend.position = "top", legend.direction = "horizontal")

  } else {
  
    warning("Please check anti-join status. There are counties NOT BEING JOINED.")
      
  }
```

```{r rig_count_change}
## An initial data frame to hold summarized data
init_calc <- rc_master %>%
  filter(PublishDate == max(PublishDate) | PublishDate == sort(unique(PublishDate), TRUE)[2]) %>%
  group_by(`State/Province`, `County`, `DrillFor`, PublishDate) %>%
  summarize(n = n()) %>%
  ungroup()

## Which locations are missing for one particular date
#  but present in the other
miss_loc <- init_calc %>%
  group_by(`State/Province`, County, DrillFor) %>%
  filter(n() != 2) %>%
  ungroup()

## Add missing, coerce missing `n` to 0, and summarize
summ_loc <- init_calc %>%
  split(.$PublishDate) %>%
  imap(~{
    y <- filter(miss_loc, PublishDate != .y)
    y <- mutate(y, n = 0)
    bind_rows(.x, y)
        }) %>%
  imap(~mutate(.x, PublishDate = as.Date(.y))) %>%
  bind_rows() %>%
  group_by(County, DrillFor, `State/Province`) %>%
  arrange(PublishDate) %>%
  mutate(change = n - lag(n, 1L)) %>%
  ungroup()

## Find if any are still unresolved
unresolved <- summ_loc %>%
  group_by(`State/Province`, County, DrillFor) %>%
  filter(n() != 2)

## Plot if none are unresolved
if (nrow(unresolved) == 0) {
  
  summ_loc %>%
    filter(PublishDate == max(PublishDate)) %>%
    inner_join(counties_2014_adjusted, c("State/Province" = "state_name", "County" = "NAME")) %>%
    st_as_sf() %>%
    ggplot() +
    geom_sf(data = us_map, fill = "gray80", color = "gray90") +
    geom_sf(aes(fill = factor(sign(change)))) +
    coord_sf(datum = NA) +
    scale_fill_manual(paste0("Change from", "\nprevious week:"), values = c(clrs$red, "gray50", clrs$blue), labels = c("Decrease", "No Change", "Increase")) +
    facet_wrap(~DrillFor, ncol = 1) +
    labs(title = paste0("Weekly change in US county oil and gas", "\nrig count"),
         subtitle = paste0("Current week: ", max(rc_master$PublishDate))) +
    theme(strip.text = element_text(size = 14),
          legend.position = "top",
          legend.direction = "horizontal")
  
} else {
  
  warning("Please check unresolved locations. There are locations for one date but not for the other.")
  
}
```



<!-- Convert for Vega and D3 -->

```{r export_counties_for_vega, eval=FALSE, include=FALSE}
## Create unique id's for observations in rig count
#  data
main <- rig_type_each %>%
  group_by(`State/Province`, County) %>%
  mutate(num = n()) %>%
  ungroup() %>%
  left_join(counties_2014_adjusted, c("County" = "NAME", "State/Province" = "state_name"))

main$id <- seq_len(nrow(main))

main <- main %>%
  select(id, `State/Province`, ADMIN_NAME,
         DrillFor, n, num)

## These counties have associated rig count data
geo_with_data <- rig_type_each %>%
    group_by(`State/Province`, County) %>%
    mutate(num = n()) %>%
    ungroup() %>%
    semi_join(counties_2014_adjusted, ., c("NAME" = "County", "state_name" = "State/Province"))

## These counties have no associated rig count data
geo_without_data <- rig_type_each %>%
    group_by(`State/Province`, County) %>%
    mutate(num = n()) %>%
    ungroup() %>%
    anti_join(counties_2014_adjusted, ., c("NAME" = "County", "state_name" = "State/Province"))

## Create id column in sf data which has associated
#  data
geo_with_data <- main %>%
    select(id, `State/Province`, ADMIN_NAME) %>%
    inner_join(geo_with_data, ., c("state_name" = "State/Province", "ADMIN_NAME" = "ADMIN_NAME"))

## Assign remaining id's to sf data which has no
#  associated data.
geo_without_data$id <- seq.int(max(geo_with_data$id) + 1L,
                               sum(nrow(geo_with_data),
                                   nrow(geo_without_data)),
                               1L)

main <- main %>%
  rename(state_name = `State/Province`,
         county = ADMIN_NAME)

geo <- geo %>%
  select(id, geometry)

write_csv(main, "C:/Users/Luke/Vega/data/main.csv")
topojson_write(geo,
               geometry = "polygon",
               file = "C:/Users/Luke/Vega/data/geo.json",
               group = "counties",
               crs = st_crs(geo))
```
